composer.json, config/install/core.entity_form_display.user.user.register.yml, config/install/field.field.user.user.field_phone_number.yml, config/install/field.storage.user.field_phone_number.yml, modules/rte_mis_school/rte_mis_school.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-5
---
- Added the phone number field for user.
- Fixed the SMS OTP issue.
=> RTEMIS-5: Added the phone number field for user.

config/install/password_policy.password_policy.school_password_policy.yml, config/install/user.settings.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-20
---
- Updated the password policy for anonymous user.
---
- Updated the policy of anonymous user and validated the password  policy.
=> RTEMIS-20: Updated the password policy for anonymous user.

modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_udise_code.yml, modules/rte_mis_school/config/install/field.storage.mini_node.field_udise_code.yml, modules/rte_mis_school/rte_mis_school.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-58
---
- Added the select list for UDISE code.
=> RTEMIS-58: Added the select list for UDISE code.

modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.default.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-58
---
- Updated the form display for select2.
=> RTEMIS-58: Updated the form display for select2.

composer.json, modules/rte_mis_core/config/schema/rte_mis_core.schema.yml, modules/rte_mis_core/rte_mis_core.install, modules/rte_mis_core/src/Batch/LocationTermBatch.php, modules/rte_mis_core/src/Form/RteMisCoreConfigForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-23
---
- Changes the location_schema term.
- Fixes the cshs filtering first level options.
- Removed multiple rural/urban option from config form.
---
- Uploaded location in batch process in different levels.
=> RTEMIS-23: Updated location_schema terms.

modules/rte_mis_core/config/install/rte_mis_core.settings.yml, modules/rte_mis_core/config/schema/rte_mis_core.schema.yml, modules/rte_mis_core/src/Form/RteMisCoreConfigForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-60
---
- Added the entry class configuration.
---
=> RTEMIS-60: Added the entry class configuration.

modules/rte_mis_core/config/install/rte_mis_core.settings.yml, modules/rte_mis_core/config/schema/rte_mis_core.schema.yml, modules/rte_mis_core/rte_mis_core.install, modules/rte_mis_core/src/Batch/LocationTermBatch.php, modules/rte_mis_core/src/Form/BulkUploadLocationForm.php, modules/rte_mis_core/src/Form/RteMisCoreConfigForm.php, modules/rte_mis_school/src/Form/BulkUploadUdiseCodeForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-23
---
- Fixes categorization(U/R) in bulk upload location.
=> RTEMIS-23: Fixed categorization(U/R) in bulk upload location.

config/install/user.role.state_admin.yml, modules/rte_mis_core/rte_mis_core.permissions.yml, modules/rte_mis_core/rte_mis_core.routing.yml, modules/rte_mis_core/src/Form/RteMisCoreConfigForm.php
---
- Added the state level permission for entry class.
=> RTEMIS-60: Added the state level permission for entry class.

config/install/user.role.state_admin.yml, modules/rte_mis_state/config/install/core.entity_form_display.mini_node.campaign.default.yml, modules/rte_mis_state/config/install/core.entity_form_display.paragraph.date_range.default.yml, modules/rte_mis_state/config/install/core.entity_view_display.mini_node.campaign.default.yml, modules/rte_mis_state/config/install/core.entity_view_display.paragraph.date_range.default.yml, modules/rte_mis_state/config/install/eck.eck_type.mini_node.campaign.yml, modules/rte_mis_state/config/install/field.field.mini_node.campaign.field_academic_year.yml, modules/rte_mis_state/config/install/field.field.mini_node.campaign.field_campaign_items.yml, modules/rte_mis_state/config/install/field.field.paragraph.date_range.field_date.yml, modules/rte_mis_state/config/install/field.field.paragraph.date_range.field_event_type.yml, modules/rte_mis_state/config/install/field.storage.mini_node.field_academic_year.yml, modules/rte_mis_state/config/install/field.storage.mini_node.field_campaign_items.yml, modules/rte_mis_state/config/install/field.storage.paragraph.field_date.yml, modules/rte_mis_state/config/install/field.storage.paragraph.field_event_type.yml, modules/rte_mis_state/config/install/paragraphs.paragraphs_type.date_range.yml, modules/rte_mis_state/rte_mis_state.info.yml, modules/rte_mis_state/rte_mis_state.module, rte_mis.info.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-66
---
- Added the campaign mini node.
- Configured campaign permission for state admin.
=> RTEMIS-66: Added the campaign mini node.

modules/rte_mis_state/config/install/core.entity_form_display.mini_node.campaign.default.yml, modules/rte_mis_state/config/install/core.entity_view_display.mini_node.campaign.default.yml, modules/rte_mis_state/config/install/field.field.mini_node.campaign.field_activate_campaign.yml, modules/rte_mis_state/config/install/field.storage.mini_node.field_activate_campaign.yml, modules/rte_mis_state/rte_mis_state.module, modules/rte_mis_state/rte_mis_state.services.yml, modules/rte_mis_state/src/Access/UserRegisterAccessCheck.php, modules/rte_mis_state/src/Helper/RteStateHelper.php, modules/rte_mis_state/src/Routing/RouteSubscriber.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-67
---
- Added the Access check for School Registration.
- Added the campaign active field
- Changed the create account link title
=> RTEMIS-67: Added the Access check for School Registration.

composer.json, config/install/system.date.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-67
---
- Added the form control patch to fix the permission issue error.
=> RTEMIS-67: Added the form control patch to fix the permission issue error.

composer.json, modules/rte_mis_state/rte_mis_state.module, rte_mis.info.yml
Ticket # : Added field permission module dependency.
---
- Added field permission module dependency.
---
=> RTEMIS-67: Added field permission module dependency.

modules/rte_mis_core/rte_mis_core.module, modules/rte_mis_state/config/install/core.entity_form_display.mini_node.admin_details.default.yml, modules/rte_mis_state/config/install/core.entity_view_display.mini_node.admin_details.default.yml, modules/rte_mis_state/config/install/eck.eck_type.mini_node.admin_details.yml, modules/rte_mis_state/config/install/field.field.mini_node.admin_details.field_authority_name.yml, modules/rte_mis_state/config/install/field.field.mini_node.admin_details.field_designation.yml, modules/rte_mis_state/config/install/field.field.user.user.field_admin_details.yml, modules/rte_mis_state/config/install/field.storage.mini_node.field_authority_name.yml, modules/rte_mis_state/config/install/field.storage.mini_node.field_designation.yml, modules/rte_mis_state/config/install/field.storage.user.field_admin_details.yml, modules/rte_mis_state/rte_mis_state.info.yml, modules/rte_mis_state/rte_mis_state.module, rte_mis.info.yml
---
- Moved the config files to rte_mis_school module.
=> RTEMIS-64: Moved the config files to rte_mis_state module.

modules/rte_mis_school/config/install/views.view.school_udise_code.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-74
---
- Fixes:  bugs in school UDISE code.
=> RTEMIS-74: Fix bugs in UDISE code.

modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_school/src/Plugin/Menu/AlterTaxonomyLocalTask.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-75
---
- Fixes: user gets redirected to school UDISE code.
=> RTEMIS-75: Alter delete local task for taxonomy.

config/install/system.site.yml
Ticket # : N/A
---
- Updated the site email id.
---
=> RTEMIS-0: Updated the site email id.

config/install/field.storage.mini_node.field_authority_name.yml, config/install/field.storage.mini_node.field_designation.yml, config/install/field.storage.user.field_admin_details.yml, config/install/field.storage.user.field_location_details.yml, config/install/user.role.district_admin.yml, config/install/user.role.state_admin.yml, modules/rte_mis_state/rte_mis_state.module
---
- State And district admin can create acc for below hierarchy level users.
- Users cannot change their role by themself.
- Config permissions for state and district users.
=> RTEMIS-64: Config changes and some feature updates.

composer.json
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-73
---
- Fixes: destination parameter in translation overview page.
=> RTEMIS-73: Added destination for translation overview.

config/install/user.role.district_admin.yml, config/install/user.role.state_admin.yml, modules/rte_mis_state/rte_mis_state.module, modules/rte_mis_state/rte_mis_state.permissions.yml
---
- Removed User role Permission for state and district admin.
=> RTEMIS-64: Removed User role Permission for state and district admin.

modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_state/rte_mis_state.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-55
---
- Added the UDISE as username for school users.
---
=> RTEMIS-55: Added the UDISE as username for school users.

modules/rte_mis_mail/rte_mis_mail.module, src/Form/SiteConfigureForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-24
---
- Fixes: Updated config keys for mail verification.
- change: Update site mail.
=> RTEMIS-24: Updated config keys for mail verification.

modules/rte_mis_state/rte_mis_state.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-59
---
- District admin will only get those UDISE codes for approval that fall under his or her district.
=> RTEMIS-59: Modified the query for school udise code view.

modules/rte_mis_state/rte_mis_state.module
Ticket # : N/A
---
- Fixed the form issue of state admins.
---
=> RTEMIS-0: Fixed the form issue of state admins.

config/install/core.entity_view_display.user.user.default.yml, config/install/core.entity_view_display.user.user.full.yml, config/install/user.role.authenticated.yml, config/install/views.view.school_basic_information.yml, config/install/views.view.user_basic_information.yml, modules/rte_mis_school/rte_mis_school.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-55
---
- Added the user info & school info on profile view.
---
=> RTEMIS-55: Added the user info & school info on profile view.

modules/rte_mis_state/rte_mis_state.module
Ticket # : N/A
---
- Added the active campaign check.
---
=> RTEMIS-0: Added the active campaign check.

modules/rte_mis_state/rte_mis_state.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-59
- Fixed the implode issue.
=> RTEMIS-59: Condition check to pass only array in implode.

config/install/user.role.district_admin.yml, modules/rte_mis_state/config/install/field.storage.paragraph.field_event_type.yml, modules/rte_mis_state/rte_mis_state.module
Ticket # : N/A
---
- Added the logic to validate current campaign item.
---
=> RTEMIS-0: Added the logic to validate current campaign item.

composer.json, modules/rte_mis_core/src/EventSubscriber/RouteRedirectSubscriber.php, modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.default.yml, modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.school_detail_edit.yml, modules/rte_mis_school/config/install/core.entity_form_display.paragraph.education_level.default.yml, modules/rte_mis_school/config/install/core.entity_view_display.mini_node.school_details.default.yml, modules/rte_mis_school/config/install/core.entity_view_display.paragraph.education_level.default.yml, modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_education_details.yml, modules/rte_mis_school/config/install/field.field.paragraph.education_level.field_board_type.yml, modules/rte_mis_school/config/install/field.field.paragraph.education_level.field_education_level.yml, modules/rte_mis_school/config/install/field.field.paragraph.education_level.field_education_level_from.yml, modules/rte_mis_school/config/install/field.field.paragraph.education_level.field_education_level_to.yml, modules/rte_mis_school/config/install/field.field.paragraph.education_level.field_education_type.yml, modules/rte_mis_school/config/install/field.field.paragraph.education_level.field_medium.yml, modules/rte_mis_school/config/install/field.storage.mini_node.field_education_details.yml, modules/rte_mis_school/config/install/field.storage.paragraph.field_board_type.yml, modules/rte_mis_school/config/install/field.storage.paragraph.field_education_level.yml, modules/rte_mis_school/config/install/field.storage.paragraph.field_education_level_from.yml, modules/rte_mis_school/config/install/field.storage.paragraph.field_education_level_to.yml, modules/rte_mis_school/config/install/field.storage.paragraph.field_education_type.yml, modules/rte_mis_school/config/install/field.storage.paragraph.field_medium.yml, modules/rte_mis_school/config/install/paragraphs.paragraphs_type.education_level.yml, modules/rte_mis_school/config/install/rte_mis_school.settings.yml, modules/rte_mis_school/rte_mis_school.info.yml, modules/rte_mis_school/rte_mis_school.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-57
=> RTEMIS-57: School details static details.

modules/rte_mis_core/src/EventSubscriber/RouteRedirectSubscriber.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-57
---
- Fixes: desination parameter in route subscriber.
=> RTEMIS-57: Updated desination parameter in route subscriber.

composer.json, config/install/autologout.settings.yml, config/install/captcha.captcha_point.user_login_form.yml, config/install/captcha.captcha_point.user_register_form.yml, config/install/captcha.settings.yml, config/install/image_captcha.settings.yml, rte_mis.info.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-81
---
-  Added the autologout & Captcha.
---
=> RTEMIS-81: Added the autologout & Captcha.

config/install/user.role.state_admin.yml, modules/rte_mis_school/config/install/views.view.school_udise_code.yml, modules/rte_mis_school/src/Batch/SchoolUdiseCodeBatch.php, modules/rte_mis_school/src/Plugin/Field/FieldWidget/TextfieldToIntegerFieldWidget.php
---
- Defined Proper error messages.
- State admin can upload bulk school udise code.
- Defined a limit for the school udise code length.
- Added a new field created by/modified by on the udise overview page.
---
https://www.awesomescreenshot.com/video/25761310?key=91d185d0f6573e163cfd0fbf3c5667eb
=> RTEMIS-78: Enhanced School Udise Configuration.

composer.json, modules/rte_mis_core/rte_mis_core.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-82
---
- Added the consent message in login & registration form.
---
=> RTEMIS-82: Added the consent message in login & registration form.

modules/rte_mis_state/rte_mis_state.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-59
---
- Only individual data will be shown to district admin.
- Fixed a bug, if user has no location defined, no data should be shown.
---
- District user should be shown Individual udise information.
- If the district admin has no location defined, no data is shown.
=> RTEMIS-59: fixed Bug related to individual data.

composer.json, modules/rte_mis_mail/config/optional/block.block.gin_reset_password.yml, modules/rte_mis_mail/rte_mis_mail.info.yml, modules/rte_mis_mail/rte_mis_mail.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-26
---
- Added the reset password module & block.
---
=> RTEMIS-26: Added the reset password module & block.

composer.json, modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.default.yml, modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.school_detail_edit.yml, modules/rte_mis_school/config/install/core.entity_form_display.paragraph.entry_class.default.yml, modules/rte_mis_school/config/install/core.entity_view_display.mini_node.school_details.default.yml, modules/rte_mis_school/config/install/core.entity_view_display.paragraph.entry_class.default.yml, modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_default_entry_class.yml, modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_entry_class.yml, modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_optional_entry_class.yml, modules/rte_mis_school/config/install/field.field.paragraph.entry_class.field_education_type.yml, modules/rte_mis_school/config/install/field.field.paragraph.entry_class.field_entry_class.yml, modules/rte_mis_school/config/install/field.storage.mini_node.field_default_entry_class.yml, modules/rte_mis_school/config/install/field.storage.mini_node.field_entry_class.yml, modules/rte_mis_school/config/install/field.storage.mini_node.field_optional_entry_class.yml, modules/rte_mis_school/config/install/field.storage.paragraph.field_entry_class.yml, modules/rte_mis_school/config/install/paragraphs.paragraphs_type.entry_class.yml, modules/rte_mis_school/config/install/rte_mis_school.settings.yml, modules/rte_mis_school/js/entry_class.js, modules/rte_mis_school/rte_mis_school.install, modules/rte_mis_school/rte_mis_school.libraries.yml, modules/rte_mis_school/rte_mis_school.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-61
---
- Implemented entry_class feature in school_details.
=> RTEMIS-61: Implemented entry_class feature in school_details.

config/install/config_ignore.settings.yml, config/install/field.field.user.user.field_phone_number.yml, modules/rte_mis_mail/js/rte_mis_mail_resend_timer.js, modules/rte_mis_mail/rte_mis_mail.libraries.yml, modules/rte_mis_mail/rte_mis_mail.module, modules/rte_mis_mail/src/Element/RteMobileNumber.php, modules/rte_mis_mail/src/Services/OtpService.php, modules/rte_mis_school/rte_mis_school.module, rte_mis.info.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-83
---
- Added the resend timer for Email & Mobile verification.
---
=> RTEMIS-83: Added the resend timer for Email & Mobile verification.

composer.json, config/install/user.role.district_admin.yml, config/install/user.role.state_admin.yml, modules/rte_mis_state/rte_mis_state.module
---
- Modified logic for user register forms.
=> RTEMIS-64: Modified the logic for the user forms.

config/install/user.role.district_admin.yml, config/install/user.role.state_admin.yml, config/install/views.view.school_udise_code.yml, modules/rte_mis_state/rte_mis_state.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-59
---
- Operations will not be visible to block admin.
- Operations will be visible to the above hierarchy but the add child has been removed.
- If an udise is approved. It will not be displayed in the approval panel.
- Changed the name from Operation to Action on overview panel.
---
=> RTEMIS-59: Review Fixes.

.lando.yml, .lando/php.ini, composer.json, modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.default.yml, modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.school_detail_edit.yml, modules/rte_mis_school/config/install/core.entity_view_display.mini_node.school_details.default.yml, modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_full_address.yml, modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_geolocation.yml, modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_location.yml, modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_pincode.yml, modules/rte_mis_school/config/install/field.storage.mini_node.field_full_address.yml, modules/rte_mis_school/config/install/field.storage.mini_node.field_geolocation.yml, modules/rte_mis_school/config/install/field.storage.mini_node.field_location.yml, modules/rte_mis_school/config/install/field.storage.mini_node.field_pincode.yml, modules/rte_mis_school/config/install/field.storage.mini_node.field_udise_code.yml, modules/rte_mis_school/js/cshs_validation.js, modules/rte_mis_school/rte_mis_school.info.yml, modules/rte_mis_school/rte_mis_school.libraries.yml, modules/rte_mis_school/rte_mis_school.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-97
---
- Added location field in school_details mini node.
=> RTEMIS-97: Added location field in school_details mini node.

modules/rte_mis_school/src/Batch/SchoolUdiseCodeBatch.php
---
- Formatted the warning message.
---
=> RTEMIS-78: Formatted the warning message and fixed an warning.

modules/rte_mis_core/src/Form/BulkUploadLocationForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-77
---
- Detailed message.
=> RTEMIS-77: Modified the error message.

config/install/views.view.school_udise_code.yml, modules/rte_mis_state/rte_mis_state.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-53
---
- Changed sorting on overview page.
- Renamed URL path from /approved to /pending-request.
- Only pending request will be avaliable in pending-request.
- District admin can now only add udise coming under their district.
=> RTEMIS-59: Made modification for overview and pending-request panel for district user.

composer.json
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-98
---
- Fixed autologout undefined issue.
=> RTEMIS-98: Fixed autologout undefined issue.

composer.json, config/install/menu_export.export_data.yml, rte_mis.info.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-69
---
- Enabled menu export and gin toolbar custom menu.
- Applied a patch to fix the null id issue.
=> RTEMIS-69: Fixed Menu load issue.

modules/rte_mis_mail/rte_mis_mail.module, modules/rte_mis_school/rte_mis_school.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-100
---
- For password recovery mail and sms both will be send.
- School Admin when changes its data, username will not change.
---
=> RTEMIS-100: Forget Password Recovery.

modules/rte_mis_core/src/Batch/LocationTermBatch.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-77
---
- Modified Error message.
=> RTEMIS-77: Modified Error message.

composer.json, config/install/user_history.settings.yml, patches/null_remove.patch, rte_mis.info.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-50
---
- Installed and enabled user history module.
- Added a custom patch.
---
=> RTEMIS-64: Implemented status tracking for user entity.

rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-69
---
- Auto Import menu links.
=> RTEMIS-69: Auto Import menus.

config/install/views.view.watchdog.yml, modules/rte_mis_school/rte_mis_school.routing.yml, modules/rte_mis_school/src/Batch/SchoolUdiseCodeBatch.php, modules/rte_mis_school/src/Controller/FailedBulkDownload.php
---
- Added Download button to download text field.
=> RTEMIS-78: Display the view and added a download button.

composer.json, config/install/user.role.block_admin.yml, modules/rte_mis_core/config/install/field.storage.taxonomy_term.field_type_of_area.yml, modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.default.yml, modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.school_detail_edit.yml, modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_habitations.yml, modules/rte_mis_school/config/install/field.storage.mini_node.field_habitations.yml, modules/rte_mis_school/config/install/rte_mis_school.settings.yml, modules/rte_mis_school/config/install/views.view.school_mapping_logs.yml, modules/rte_mis_school/rte_mis_school.links.menu.yml, modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_school/rte_mis_school.permissions.yml, modules/rte_mis_school/rte_mis_school.routing.yml, modules/rte_mis_school/src/Form/SchoolMappingForm.php, rte_mis.info.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-32
---
- Added the school mapping interface.
- Added the logic to fetch the habitation list.
---
=> RTEMIS-32: Added School Mapping Interface.

modules/rte_mis_core/rte_mis_core.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-69
---
- Removed the Tools menu for non-admin users.
---
=> RTEMIS-69: Removed the Tools menu for non-admin users.

config/install/menu_export.export_data.yml, modules/rte_mis_mail/rte_mis_mail.module, modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_school/rte_mis_school.routing.yml, modules/rte_mis_state/rte_mis_state.services.yml, modules/rte_mis_state/src/Access/UserRegisterAccessCheck.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-26
---
- Added the UDISE in forgot password.
---
=> RTEMIS-26: Added the UDISE in forgot password.

config/install/views.view.school_udise_code.yml, config/install/views.view.watchdog.yml, modules/rte_mis_school/src/Batch/SchoolUdiseCodeBatch.php, modules/rte_mis_school/src/Controller/FailedBulkDownload.php, modules/rte_mis_school/src/Plugin/Field/FieldWidget/TextfieldToIntegerFieldWidget.php
---
- Only the logged-in user can see their message and download the Excel file.
- The download file option should be visible on failed uploads only.
- Added sort and filter to the overview panel.
- failed udise bulk only visible to app admin.
- Length of udise code should be exactly 11.
=> RTEMIS-78: Modified the udise overview view and bulk upload message.

modules/rte_mis_school/src/Batch/SchoolBatch.php, modules/rte_mis_state/rte_mis_state.module
---
- District user can add school under his district.
- Fixed permission issue for state and district admin.
- Fixed caching issue for the pending request panel.
=> RTEMIS-78: Fixed Caching issue & Permissions issue.

composer.json, modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.school_detail_edit.yml, modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_school_verification.yml, modules/rte_mis_school/rte_mis_school.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-31
---
- Fixes: Updated the workflow transition for school/school_admins.
=> RTEMIS-62: Updated the workflow transition for school/school_admins.

modules/rte_mis_school/src/Form/SchoolMappingForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-32
---
- For a particular district & block selected,Nagriya nikae of other district were also loaded.
---
- For a particular district & block selected,Nagriya nikae of only the selected district is loaded.
- Tested from block admin and app admin user role.
---
https://www.awesomescreenshot.com/video/26458278?key=c4b02fe97d23a8f087e1d9caf50008b6
=> RTEMIS-32: Fixed Multiple Nagriya nikae load issue.

modules/rte_mis_school/src/Batch/SchoolBatch.php
---
- Fixed Bug for different locations of the district.
=> RTEMIS-78: Fixed Bug for different location of district.

modules/rte_mis_mail/src/Form/RteMisMailConfigForm.php, modules/rte_mis_state/rte_mis_state.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-105
---
- Whenever the state gets changed, mail & sms will be triggered.
- Modified the email & sms panel to add the option to configure the school status notification
---
- mails are triggered.
- SMS are sent.
---
=> RTEMIS-105: School Verification Update notification.

modules/rte_mis_state/rte_mis_state.info.yml, rte_mis.info.yml
Ticket # : N/A
---
- Added the entity form field label as dependency.
---
=> RTEMIS-0: Added the entity form field label as dependency.

modules/rte_mis_state/rte_mis_state.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-105
---
-  Added Condition for entity check.
=> RTEMIS-105: Added Condition for entity check.

modules/rte_mis_core/rte_mis_core.module, modules/rte_mis_mail/src/Form/RteMisMailConfigForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-113
---
- Fixed the sms message maxlength.
---
=> RTEMIS-113: Fixed the sms message maxlength.

modules/rte_mis_school/config/install/field.field.taxonomy_term.school.field_declaration.yml, modules/rte_mis_state/rte_mis_state.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-113
---
-  Fixed minor issues of enhancement
=> RTEMIS-113: Fixed minor issues.

modules/rte_mis_mail/src/Form/RteMisMailConfigForm.php
Ticket # : [innoraft.atlassian.net/browse/RTEMIS-105](https://innoraft.atlassian.net/browse/RTEMIS-105)
---
- Notification SMS wordcount fixed.
=> RTEMIS-105: Fixed the notification SMS wordcount.

config/install/menu_export.export_data.yml, config/install/user.role.block_admin.yml, config/install/user.role.district_admin.yml, config/install/user.role.school.yml, config/install/user.role.school_admin.yml, config/install/views.view.school_registration.yml, modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.default.yml, modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.school_detail_edit.yml, modules/rte_mis_school/config/install/core.entity_view_display.mini_node.school_details.default.yml, modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_verification_approval_date.yml, modules/rte_mis_school/config/install/field.storage.mini_node.field_verification_approval_date.yml, modules/rte_mis_school/config/install/workflow.transition.school_registration_verification_send_back_to_school_approved_by_beo.yml, modules/rte_mis_school/config/install/workflow.transition.school_registration_verification_send_back_to_school_rejected.yml, modules/rte_mis_school/rte_mis_school.links.task.yml, modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_school/rte_mis_school.routing.yml, modules/rte_mis_school/rte_mis_school.services.yml, modules/rte_mis_school/src/Access/SchoolDetailViewAccessCheck.php, modules/rte_mis_school/src/Routing/RouteSubscriber.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-87
---
-  Implemented School Registration Modification.
=> RTEMIS-87: Implemented School Registration Modification.

config/install/user.role.district_admin.yml, modules/rte_mis_core/src/Batch/LocationTermBatch.php, modules/rte_mis_school/config/install/field.field.paragraph.entry_class.field_education_type.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-117
---
- Fixed minor issues.
=> RTEMIS-117: Fixed minor issues.

modules/rte_mis_school/config/install/core.entity_form_display.paragraph.education_level.default.yml, modules/rte_mis_school/config/install/core.entity_form_display.paragraph.fee_details.default.yml, modules/rte_mis_school/config/install/core.entity_view_display.paragraph.education_level.default.yml, modules/rte_mis_school/config/install/core.entity_view_display.paragraph.fee_details.default.yml, modules/rte_mis_school/config/install/field.field.paragraph.education_level.field_fee_details.yml, modules/rte_mis_school/config/install/field.field.paragraph.fee_details.field_class_list.yml, modules/rte_mis_school/config/install/field.field.paragraph.fee_details.field_total_fees.yml, modules/rte_mis_school/config/install/field.storage.paragraph.field_class_list.yml, modules/rte_mis_school/config/install/field.storage.paragraph.field_fee_details.yml, modules/rte_mis_school/config/install/field.storage.paragraph.field_total_fees.yml, modules/rte_mis_school/config/install/paragraphs.paragraphs_type.fee_details.yml, modules/rte_mis_school/rte_mis_school.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-115
---
-  Added fee details paragraph, and used that in educational details paragraph.
- Set default value for fee details class list field.
- Values in class list will be updated dynamically.
- Added validation for a education entry user cannot add multiple fees details of same class.
=> RTEMIS-115: Added Fees details section.

modules/rte_mis_school/config/install/field.field.paragraph.fee_details.field_class_list.yml, modules/rte_mis_school/rte_mis_school.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-115
---
- Added more checks and modified the logic.
=> RTEMIS-115: modified the logic for education detail status.

config/install/user.role.district_admin.yml, config/install/user.role.state_admin.yml, modules/rte_mis_school/config/install/rte_mis_school.settings.yml, modules/rte_mis_school/config/schema/rte_mis_school.schema.yml, modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_school/rte_mis_school.permissions.yml, modules/rte_mis_school/rte_mis_school.routing.yml, modules/rte_mis_school/rte_mis_school.services.yml, modules/rte_mis_school/src/Access/SchoolDetailEditAccessCheck.php, modules/rte_mis_school/src/Form/RteMisSchoolConfigForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-89
---
- Implemented single approval for school verification.
=> RTEMIS-89: Implemented single approval for school verification.

modules/rte_mis_school/rte_mis_school.links.menu.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-89
---
- Added menu link for rte_mis_school config form.
=> RTEMIS-89: Added menu link for rte_mis_school config form.

composer.json
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-121
---
- Added patch for conditional_field.
=> RTEMIS-121: Added patch for conditional_field.

modules/rte_mis_student/rte_mis_student.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-121
---
-  Fixed validation issue for sibling_details.
=> RTEMIS-121: Fixed validation issue for sibling_details.

.gitignore, modules/rte_mis_core/src/Plugin/Block/SiteLogoSectionBlock.php, modules/rte_mis_gin/gulpfile.js, modules/rte_mis_gin/js/script.js, modules/rte_mis_gin/package.json, modules/rte_mis_gin/rte_mis_gin.info.yml, modules/rte_mis_gin/rte_mis_gin.libraries.yml, modules/rte_mis_gin/rte_mis_gin.module, modules/rte_mis_gin/scss/base/_breakpoints.scss, modules/rte_mis_gin/scss/base/_color.scss, modules/rte_mis_gin/scss/base/_reset.scss, modules/rte_mis_gin/scss/main.scss, modules/rte_mis_gin/scss/navigation/_footer.scss, modules/rte_mis_gin/templates/block--sitelogo.html.twig, modules/rte_mis_gin/templates/page--custom.html.twig, modules/rte_mis_gin/templates/region--content.html.twig, modules/rte_mis_gin/templates/region--header.html.twig, rte_mis.info.yml
---
- Footer section design.
- Basic theme setup.
=> RTEMIS-128: Basic theme setup and footer theming.

modules/rte_mis_gin/package.json
=> RTEMIS-128: Node version upgrade.

modules/rte_mis_student/config/install/rte_mis_student.settings.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-54
---
- Updated option for EWS Category.
=> RTEMIS-54: Updated option for EWS Category.

modules/rte_mis_gin/js/script.js, modules/rte_mis_gin/rte_mis_gin.module, modules/rte_mis_gin/scss/main.scss, modules/rte_mis_gin/scss/navigation/_footer.scss, modules/rte_mis_gin/scss/navigation/_header.scss, modules/rte_mis_gin/templates/block--mainmenu.html.twig, modules/rte_mis_gin/templates/page--custom.html.twig, modules/rte_mis_gin/templates/region--rtebreadcrumb.html.twig
=> RTEMIS-128: Main menu theming and structure.

modules/rte_mis_gin/rte_mis_gin.module, modules/rte_mis_gin/scss/layout/_user-login-page.scss, modules/rte_mis_gin/scss/main.scss, modules/rte_mis_gin/scss/navigation/_footer.scss, modules/rte_mis_gin/templates/page--user-login.html.twig, modules/rte_mis_gin/templates/page--user-password.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-129
---
---
---
=> RTEMIS-129: Login and reset password form theming.

modules/rte_mis_gin/rte_mis_gin.module, modules/rte_mis_gin/scss/layout/_user-register-page.scss, modules/rte_mis_gin/scss/main.scss, modules/rte_mis_gin/scss/navigation/_footer.scss, modules/rte_mis_gin/templates/page--user-register.html.twig
=> RTEMIS-130: School registration form theming.

modules/rte_mis_gin/js/script.js, modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/main.scss, modules/rte_mis_gin/scss/navigation/_footer.scss, modules/rte_mis_gin/scss/navigation/_header.scss
=> RTEMIS-128: Header and footer theming updates.

config/install/menu_export.export_data.yml, config/install/views.view.school_registration.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-89
---
- Updated menu for district and block admin.
=> RTEMIS-89: Updated menu for district and block admin.

composer.json, config/install/config_ignore.settings.yml, config/install/user.role.anonymous.yml, modules/rte_mis_student/config/install/core.entity_form_display.mini_node.student_details.default.yml, modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.default.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_mobile_number.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_student_name.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_mobile_number.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_student_name.yml, modules/rte_mis_student/config/install/rte_mis_student.settings.yml, modules/rte_mis_student/config/install/views.view.student_applications.yml, modules/rte_mis_student/js/rte_mis_student_resend_timer.js, modules/rte_mis_student/rte_mis_student.info.yml, modules/rte_mis_student/rte_mis_student.install, modules/rte_mis_student/rte_mis_student.libraries.yml, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/rte_mis_student.routing.yml, modules/rte_mis_student/rte_mis_student.services.yml, modules/rte_mis_student/src/Access/StudentDetailEditAccessCheck.php, modules/rte_mis_student/src/Access/StudentRegisterAccessCheck.php, modules/rte_mis_student/src/Controller/StudentApplicationController.php, modules/rte_mis_student/src/EventSubscriber/StudentLoginEventSubscriber.php, modules/rte_mis_student/src/Form/RteMisStudentConfigForm.php, modules/rte_mis_student/src/Form/StudentLoginForm.php, modules/rte_mis_student/src/Routing/RouteSubscriber.php, modules/rte_mis_student/src/Services/MobileOtpService.php, modules/rte_mis_student/src/Services/MobileOtpServiceInterface.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-120
---
- Implemented Student Registration feature.
=> RTEMIS-120: Implemented Student Registration feature.

modules/rte_mis_student/config/install/rte_mis_student.settings.yml, modules/rte_mis_student/rte_mis_student.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-54
---
-  Updated category for student_details.
=> RTEMIS-54: Updated category for student_details.

config/install/block.block.gin_useraccountmenu.yml, config/install/menu_export.export_data.yml, config/install/menu_export.settings.yml, config/install/user.role.anonymous.yml
---
- Added login and search button on main menu.
=> RTEMIS-128: Added login and search button on main menu.

modules/rte_mis_core/rte_mis_core.module, modules/rte_mis_gin/scss/navigation/_footer.scss, modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-30
---
---
---
=> RTEMIS-30: School print pdf theming and footer logo color chnages.

modules/rte_mis_gin/js/script.js, modules/rte_mis_gin/scss/layout/_user-register-page.scss
=> RTEMIS-130: Added the note line in school form.

modules/rte_mis_gin/js/script.js, modules/rte_mis_gin/scss/navigation/_header.scss
=> RTEMIS-128 : Header theming for child and items added.

composer.json, config/install/gin.settings.yml, config/install/gin_toolbar_custom_menu.settings.yml, config/install/menu_export.export_data.yml, rte_mis.info.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-124
---
- Added the menu links for different user roles.
---
=> RTEMIS-124: Added the menu links for different user roles.

modules/rte_mis_gin/scss/layout/_user-register-page.scss
=> RTEMIS-130: Checkbox theming updates for school form.

config/install/menu_export.export_data.yml
Ticket # :
---
- Updated the anonymous user menu link.
---
=> RTEMIS-124: Updated the anonymous user menu link.

config/install/menu_export.export_data.yml
Ticket # : N/A
---
- Added the child elements.
---
=> RTEMIS-124: Added the child elements.

modules/rte_mis_gin/scss/navigation/_footer.scss, modules/rte_mis_gin/scss/navigation/_header.scss
=> RTEMIS-128: Header and footer changes for safari browser.

modules/rte_mis_gin/scss/navigation/_header.scss
=> RTEMIS-128: Submenu childs theming on mobil and tab.

.github/workflows/code-checker.yml
Ticket # : N/A
---
- Added the code checker github workflow.
---
=> RTEMIS-0: Added the code checker github workflow.

config/install/gin_toolbar_custom_menu.settings.yml, config/install/menu_export.export_data.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-124
---
- Removed the search icon from district.
---
=> RTEMIS-124: Removed the search icon from district.

.github/workflows/phpcs.yml
Ticket # : N/A
---
- Updated the phpcs workflow file.
=> RTEMIS-0: Updated the phpcs workflow file.

config/install/user.role.school.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-124
---
- Updated the permission of school role.
---
=> RTEMIS-124: Updated the permission of school role.

modules/rte_mis_gin/gulpfile.js, modules/rte_mis_gin/js/register-form.js, modules/rte_mis_gin/js/script.js, modules/rte_mis_gin/package.json, modules/rte_mis_gin/rte_mis_gin.libraries.yml, modules/rte_mis_gin/rte_mis_gin.module, modules/rte_mis_gin/scss/layout/user-login-page.scss, modules/rte_mis_gin/scss/layout/user-register-page.scss, modules/rte_mis_gin/scss/main.scss, modules/rte_mis_gin/scss/navigation/_header.scss, modules/rte_mis_gin/templates/page--user-login.html.twig, modules/rte_mis_gin/templates/page--user-password.html.twig, modules/rte_mis_gin/templates/page--user-register.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-141
---
---
---
=> RTEMIS-141: Created different libraries for all pages.

.github/workflows/phpcs.yml
Ticket # : N/A
---
- Updated the standard in phpcs.
---
=> RTEMIS-0: Updated the standard in phpcs.

config/install/user.role.anonymous.yml, modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.pdf.yml, modules/rte_mis_student/config/install/views.view.student_applications.yml, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/rte_mis_student.services.yml, modules/rte_mis_student/src/Access/StudentPdfDownloadAccessCheck.php, modules/rte_mis_student/src/EventSubscriber/StudentLoginEventSubscriber.php, modules/rte_mis_student/src/Routing/RouteSubscriber.php, modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-131
---
- Student Application Print.
---
- Only app admin and parents can download the pdf.
=> RTEMIS-131: Student Application Print.

modules/rte_mis_gin/scss/base/_color.scss, modules/rte_mis_gin/scss/layout/user-register-page.scss
=> RTEMIS-130: Position and color changes in the form.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-30
---
---
---
`(Add Screenshots or videos)` 
[document (53).pdf](https://github.com/Indus-Action-Initiatives/rte-mis/files/15220591/document.53.pdf)
=> RTEMIS-30: Pdf theming updates.

composer.json, modules/rte_mis_student/config/install/core.entity_form_display.mini_node.student_details.default.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_has_siblings.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_hiv.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_orphan.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_single_girl_child.yml, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-121
---
- Updated the static field.
=> RTEMIS-121: Updated the static field.

modules/rte_mis_core/templates/block--site-pre-menu-text-section-block.html.twig, modules/rte_mis_gin/js/register-form.js, modules/rte_mis_gin/js/script.js, modules/rte_mis_gin/scss/navigation/_header.scss
=> RTEMIS-138: Theming of submenu.

config/install/core.entity_form_display.user.user.register.yml, config/install/field.field.user.user.field_phone_number.yml, config/install/field.storage.user.field_phone_number.yml, modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_udise_code.yml, modules/rte_mis_school/config/install/field.storage.mini_node.field_udise_code.yml, modules/rte_mis_school/rte_mis_school.module
=> RTEMIS-130: Added Placeholder for email and phone number field.

config/install/menu_export.export_data.yml, config/install/user.role.state_admin.yml, config/install/views.view.academic_sessions_list.yml, modules/rte_mis_state/rte_mis_state.links.action.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-143
---
- Created a listing page for all the campaigns.
---
- The campaign listing page and the campaign details are visible to the state admin.
---
=> RTEMIS-143: Campaign listing page.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/navigation/_header.scss, modules/rte_mis_gin/templates/page--custom.html.twig
=> RTEMIS-138: Themed the hero banner.

config/install/menu_export.export_data.yml
Ticket # : N/A
---
- Updated the school review menu link.
---
=> RTEMIS-0: Updated the school review menu link.

config/install/views.view.school_registration.yml, config/install/views.view.student_registration.yml, modules/rte_mis_student/config/install/views.view.student_applications.yml, modules/rte_mis_student/rte_mis_student.routing.yml, modules/rte_mis_student/src/Controller/StudentApplicationController.php, modules/rte_mis_student/src/Form/StudentApplicationStatusForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-133
---
- Implemented Student Application Status Feature.
=> RTEMIS-133: Implemented Student Application Status Feature.

modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-30
---
- Modified Twig.
- Added fee details data.
=> RTEMIS-30: Fee details design change.

modules/rte_mis_gin/scss/base/_global.scss
=> RTEMIS-130: Changed the breadcrumb color.

composer.json, config/install/views.view.student_registration.yml, modules/rte_mis_student/config/install/core.entity_form_display.mini_node.student_details.default.yml, modules/rte_mis_student/config/install/core.entity_form_display.paragraph.school_preference.default.yml, modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.default.yml, modules/rte_mis_student/config/install/core.entity_view_display.paragraph.school_preference.default.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_school_preferences.yml, modules/rte_mis_student/config/install/field.field.paragraph.school_preference.field_medium.yml, modules/rte_mis_student/config/install/field.field.paragraph.school_preference.field_school_id.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_school_preferences.yml, modules/rte_mis_student/config/install/field.storage.paragraph.field_school_id.yml, modules/rte_mis_student/config/install/paragraphs.paragraphs_type.school_preference.yml, modules/rte_mis_student/rte_mis_student.info.yml, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php, modules/rte_mis_student/src/Form/StudentApplicationStatusForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-123
---
- Updated school eligible feature.
=> RTEMIS-123: Updated school eligible feature.

modules/rte_mis_gin/scss/layout/user-register-page.scss
=> RTEMIS-130: Email validation message in printing once now.

modules/rte_mis_gin/scss/layout/_student-details.scss, modules/rte_mis_gin/scss/main.scss
=> RTEMIS-134: School application print form theming.

config/install/block.block.gin_mainmenu.yml, config/install/block.block.gin_sitelogosection.yml, config/install/block.block.gin_sitepremenutextheader.yml, config/install/block.block.gin_useraccountmenu.yml, config/install/easy_breadcrumb.settings.yml, config/install/gin_toolbar_custom_menu.settings.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-139
---
- Fixed menus and breadcrumbs issue.
=> RTEMIS-139: Fixed the breadcrumb position issue and modified menu icons.

modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-30
---
---
---
=> RTEMIS-30: Modification in pdf design.

modules/rte_mis_student/config/install/core.entity_form_display.mini_node.student_details.default.yml, modules/rte_mis_student/config/install/core.entity_form_display.paragraph.siblings.default.yml, modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.default.yml, modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.pdf.yml, modules/rte_mis_student/config/install/core.entity_view_display.paragraph.siblings.default.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_father_aadhar_number.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_father_name.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_gaurdian_aadhar_number.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_guardian_name.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_mother_aadhar_number.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_mother_name.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_parent_type.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_single_parent_type.yml, modules/rte_mis_student/config/install/field.field.paragraph.siblings.field_aadhaar_card.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_father_aadhar_number.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_father_name.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_gaurdian_aadhar_number.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_guardian_name.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_mother_aadhar_number.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_mother_name.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_parent_type.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_single_parent_type.yml, modules/rte_mis_student/js/rte_mis_student_aadhar_validation.js, modules/rte_mis_student/rte_mis_student.libraries.yml, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-137
---
- Added parent detail fields and added respective validations.
---
https://www.awesomescreenshot.com/video/27540934?key=80719f393c356f1bcd6a4f696bd51fd1
=> RTEMIS-137: Added the parent fields for Student Details Form.

modules/rte_mis_student/config/install/core.entity_form_display.mini_node.student_details.default.yml, modules/rte_mis_student/config/install/core.entity_form_display.paragraph.siblings.default.yml, modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.default.yml, modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.pdf.yml, modules/rte_mis_student/config/install/core.entity_view_display.paragraph.siblings.default.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_father_aadhar_number.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_father_name.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_gaurdian_aadhar_number.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_guardian_name.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_mother_aadhar_number.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_mother_name.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_parent_type.yml, modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_single_parent_type.yml, modules/rte_mis_student/config/install/field.field.paragraph.siblings.field_aadhaar_card.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_father_aadhar_number.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_father_name.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_gaurdian_aadhar_number.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_guardian_name.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_mother_aadhar_number.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_mother_name.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_parent_type.yml, modules/rte_mis_student/config/install/field.storage.mini_node.field_single_parent_type.yml, modules/rte_mis_student/js/rte_mis_student_aadhar_validation.js, modules/rte_mis_student/rte_mis_student.libraries.yml, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-137
---
- Modified the configs
---
=> RTEMIS-137: Modified the parent fields for Student Details Form.

modules/rte_mis_mail/rte_mis_mail.module
---
- Modified the label for email field.
=> RTEMIS-130: Modified the labels for the email verification field.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/layout/_student-details.scss
=> RTEMIS-138: Global theming updates for forms.

modules/rte_mis_student/config/install/core.entity_form_display.mini_node.student_details.default.yml, modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
---
- Added the label for location field.
---
###Extras
=> RTEMIS-134: Added the label for the Location field.

modules/rte_mis_student/config/install/core.entity_form_display.mini_node.student_details.default.yml, modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-137
---
- Added the markup texts.
- Modified the parent feild to radios.
---
=> RTEMIS-137: Added the markup texts.

.lando.yml, config/install/config_ignore.settings.yml, config/install/field.field.user.user.field_phone_number.yml, config/install/user.role.block_admin.yml, config/install/views.view.student_registration.yml, modules/rte_mis_school/config/install/core.entity_view_display.mini_node.school_details.default.yml, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/rte_mis_student.services.yml, modules/rte_mis_student/src/Access/StudentDetailEditAccessCheck.php, modules/rte_mis_student/src/Access/StudentRegisterAccessCheck.php, modules/rte_mis_student/src/EventSubscriber/StudentLoginEventSubscriber.php, modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php, modules/rte_mis_student/src/Form/StudentLoginForm.php, modules/rte_mis_student/src/Routing/RouteSubscriber.php, modules/rte_mis_student/src/Services/MobileOtpService.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-122
---
- Implemented student edit for block admin.
=> RTEMIS-122: Implemented student edit for block admin.

modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-126
---
- Removed the empty sibling details from entity view.
=> RTEMIS-126: Removed the empty sibling details from entity view.

modules/rte_mis_student/src/Form/StudentApplicationStatusForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-133
---
-  Rename the registration number to the application number.
=> RTEMIS-133: Rename registration number to application number.

modules/rte_mis_gin/scss/base/_color.scss, modules/rte_mis_gin/scss/layout/_student-details.scss, modules/rte_mis_gin/scss/layout/user-register-page.scss
=> RTEMIS-134: Student form theming.

modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.default.yml, modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.pdf.yml, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-131
---
- Added necessary permission.
- Modified Twig.
=> RTEMIS-131: Modified the Student Application Print.

modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.pdf.yml, modules/rte_mis_student/src/Access/StudentPdfDownloadAccessCheck.php, modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-131
---
- Added the Application Status field in the Student Pdf.
=> RTEMIS-131: Added the Application Status field in the Student Pdf.

config/install/menu_export.export_data.yml, modules/rte_mis_gin/rte_mis_gin.module
Ticket # : N/A
---
- Updated the menu links and check issue.
---
=> RTEMIS-0: Updated the menu links and check issue.

config/install/menu_export.export_data.yml, config/install/user.role.district_admin.yml, config/install/user.role.state_admin.yml, config/install/views.view.school_registration.yml, config/install/views.view.student_registration.yml, modules/rte_mis_state/rte_mis_state.module, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/src/Access/StudentDetailViewAccessCheck.php
Ticket # : NA
---
-  Updated the menus.
=> RTEMIS-00: Updated the menus.

modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-131
---
- Fixed the Rural/Urban issue.
---
=> RTEMIS-131: Fixed the Rural/Urban issue.

modules/rte_mis_gin/scss/layout/_student-details.scss
=> RTEMIS-134: Student details form theming.

modules/rte_mis_gin/scss/layout/_student-details.scss
=> RTEMIS-134: Student form theming updates.

config/install/captcha.settings.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-152
---
- Modified the Captcha Settings to make it Case Sensitive.
=> RTEMIS-152: Modified the Captcha Settings.

modules/rte_mis_gin/rte_mis_gin.module, modules/rte_mis_gin/scss/base/_global.scss
=> RTEMIS-155: School registration view node theming.

modules/rte_mis_gin/scss/base/_global.scss
=> RTEMIS-155: Student registration form theming.

composer.json, modules/rte_mis_multilingual/config/optional/block.block.gin_languagedropdownswitcher.yml, modules/rte_mis_multilingual/rte_mis_multilingual.info.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-153
---
- Moved the lang dropdown to breadcrumb region.
---
=> RTEMIS-153: Moved the lang dropdown to breadcrumb region.

modules/rte_mis_gin/scss/base/_breakpoints.scss, modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/base/_reset.scss, modules/rte_mis_gin/scss/layout/user-login-page.scss, modules/rte_mis_gin/scss/layout/user-register-page.scss, modules/rte_mis_gin/scss/navigation/_header.scss
=> RTEMIS-155: Language dropdown theming on submenu.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/layout/_student-details.scss, modules/rte_mis_gin/scss/layout/user-register-page.scss, modules/rte_mis_gin/scss/navigation/_footer.scss, modules/rte_mis_gin/scss/navigation/_header.scss
=> RTEMIS-138: Global font size 16px.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/navigation/_header.scss
=> RTEMIS-155: Content add node theming.

modules/rte_mis_core/rte_mis_core.module, modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_state/rte_mis_state.module, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-147
---
- : Resolved multiple issues(academic, language, registration section).
=> RTEMIS-159: Resolved multiple issues(academic, language, registration section).

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/navigation/_footer.scss
=> RTEMIS-138: School pending view theming.

config/install/menu_export.export_data.yml, config/install/user.role.district_admin.yml, modules/rte_mis_core/js/disable_cshs_select.js, modules/rte_mis_core/js/general.js, modules/rte_mis_core/rte_mis_core.libraries.yml, modules/rte_mis_school/src/Form/SchoolMappingForm.php, modules/rte_mis_state/rte_mis_state.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-160
---
- Resolved school mapping feedback.
=> RTEMIS-161: Resolved school mapping feedback.

config/install/administerusersbyrole.settings.yml, config/install/menu_export.export_data.yml, config/install/user.role.district_admin.yml, config/install/user.role.state_admin.yml, modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_state/rte_mis_state.module, modules/rte_mis_state/rte_mis_state.services.yml, modules/rte_mis_state/src/Access/UserEditAccessCheck.php, modules/rte_mis_state/src/Plugin/Menu/AlterPeopleActionTask.php, modules/rte_mis_state/src/Routing/RouteSubscriber.php, rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-154
---
-  Modified Menus for State and district.
- Added Custom Access Checks.
- Modified Configs for Administer User By Role.
- Modified the Action link on People Listing Page.
=> RTEMIS-154: Fixed the Admin Section BE Issues.

modules/rte_mis_gin/js/script.js, modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/layout/user-login-page.scss, modules/rte_mis_gin/scss/navigation/_header.scss
=> RTEMIS-155: Layout fixes on different viewports.

composer.json, config/install/easy_breadcrumb.settings.yml, config/install/menu_export.export_data.yml, config/install/pathauto.pattern.academic_sessions_alias.yml, config/install/pathauto.pattern.location_alias.yml, config/install/pathauto.pattern.school_alias.yml, config/install/pathauto.pattern.school_mini_node_alias.yml, config/install/pathauto.pattern.student_details_alias.yml, config/install/pathauto.settings.yml, config/install/subpathauto.settings.yml, modules/rte_mis_mail/rte_mis_mail.module, modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php, patches/breadcrumb_edit_fix.patch, rte_mis.info.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-152
---
- Fixed the breadcrumb issue.
- Modified the menu according to the front-end requirement.
=>  RTEMIS-152: Fixed the breadcrumb issue.

modules/rte_mis_core/rte_mis_core.routing.yml, modules/rte_mis_core/src/Controller/UnderConstruction.php, modules/rte_mis_gin/rte_mis_gin.libraries.yml, modules/rte_mis_gin/rte_mis_gin.module
Ticket # : N/A
---
- Added the under construction page.
---
=> RTEMIS-0: Added the under construction page.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/layout/_student-details.scss
=> RTEMIS-155: Student form theming updates.

modules/rte_mis_core/rte_mis_core.routing.yml
Ticket # : N/A
---
- Changed the the URL of the construction page.
---
=> RTEMIS-0: Changed the the URL of the construction page.

config/install/menu_export.export_data.yml, modules/rte_mis_core/rte_mis_core.module, modules/rte_mis_core/src/Plugin/Menu/AlterTaxonomyActionTask.php, modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-151
---
- Resolved multiple feedback.
=> RTEMIS-001: Resolved multiple feedback.

config/install/menu_export.export_data.yml
=> RTEMIS-10: Modified the menu links.

modules/rte_mis_gin/scss/base/_global.scss
=> RTEMIS-155: Student edit form theming updates.

modules/rte_mis_core/src/Controller/UnderConstruction.php, modules/rte_mis_gin/scss/layout/under-construction.scss
=> RTEMIS-138: Under construction page theming.

modules/rte_mis_student/src/CustomVocabularyListBuilder.php, modules/rte_mis_student/src/Routing/RouteSubscriber.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-162
---
- Location Overiview Panel.
=> RTEMIS-162: Location Overiview Panel.

modules/rte_mis_core/rte_mis_core.module, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/src/CustomVocabularyListBuilder.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-162
---
-  Location Overview Panel.
=> RTEMIS-162: Location Overview Panel.

modules/rte_mis_gin/scss/base/_global.scss
Ticket # : N/A
---
- Added the text capitalization for links.
---
=> RTEMIS-0: Added the text capitalization for links.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/layout/user-register-page.scss, modules/rte_mis_gin/scss/navigation/_footer.scss
Ticket # :  https://innoraft.atlassian.net/browse/RTEMIS-138
---
---
---
=> RTEMIS-138: Forms alignment theming.

modules/rte_mis_core/src/Form/BulkUploadLocationForm.php, modules/rte_mis_mail/rte_mis_mail.module, modules/rte_mis_mail/src/Element/RteMobileNumber.php, modules/rte_mis_school/config/install/field.field.paragraph.fee_details.field_total_fees.yml, modules/rte_mis_school/rte_mis_school.links.task.yml, modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_state/rte_mis_state.module, modules/rte_mis_student/src/Form/StudentLoginForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-154
---
- Modified School Account issues.
- Added fullscreen progress on ajax calls.
=> RTEMIS-154: Demo feedback fixes.

composer.json, config/install/entity_print.settings.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-132
=> RTEMIS-132: Added patch for entity_print.

modules/rte_mis_gin/scss/layout/user-register-page.scss
=> RTEMIS-138: Used edit form theming updates.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/layout/user-login-page.scss, modules/rte_mis_gin/scss/layout/user-register-page.scss, modules/rte_mis_gin/scss/navigation/_header.scss, modules/rte_mis_school/rte_mis_school.module
=> RTEMIS-138: Madhu feedback changes.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_state/rte_mis_state.module
Ticket # : N/A
---
- Fix the bugs of user account creation.
---
=> RTEMIS-0: Fix the bugs of user account creation.

modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-132
---
- Added the pdf changes for students.
---
---
=> RTEMIS-132: Added the pdf changes for students.

modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig, modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-132
---
- Updated the icon for pdf.
=> RTEMIS-132: Updated the icon for pdf.

modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig, modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
This reverts commit 080cde05a1891d52e94dfc066a69a683cae7885f.
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-132
---
=> Revert - RTEMIS-132: Updated the icon for pdf.

modules/rte_mis_gin/scss/layout/user-register-page.scss, modules/rte_mis_gin/scss/navigation/_footer.scss
=> RTEMIS-138: Footer mail text property modification.

config/install/block.block.gin_quicklinks.yml, config/install/menu_export.export_data.yml, config/install/user.role.state_admin.yml, config/install/views.view.administerusersbyrole_people.yml, config/install/views.view.school.yml, modules/rte_mis_school/src/Form/SchoolMappingForm.php, modules/rte_mis_state/rte_mis_state.module
=> RTEMIS-04: Fixed multiple issue.

config/install/block.block.gin_sitelogosection.yml, config/install/block.block.gin_sitelogosection_2.yml, modules/rte_mis_core/src/Plugin/Block/SiteLogoSectionBlock.php, modules/rte_mis_state/rte_mis_state.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-169
---
- Additional feedbacks.
=> RTEMIS-169: Additional feedbacks.

modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-166
---
- Modified the pdf template for school.
=> RTEMIS-166: Modified the pdf template for school.

composer.json, config/install/administerusersbyrole.settings.yml, config/install/user.role.district_admin.yml, config/install/user.role.state_admin.yml, modules/rte_mis_core/config/install/core.entity_form_display.taxonomy_term.location.default.yml, modules/rte_mis_core/rte_mis_core.module, modules/rte_mis_core/src/Form/OverrideTermForm.php, modules/rte_mis_core/src/Helper/RteCoreHelper.php, modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_state/rte_mis_state.module, rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-169
---
- Fixed multiple issues.
=> RTEMIS-05: Fixed multiple issues.

modules/rte_mis_gin/scss/layout/user-register-page.scss
=> RTEMIS-138: School register form input width.

modules/rte_mis_student/js/rte_mis_student_aadhar_validation.js, modules/rte_mis_student/rte_mis_student.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-165
---
- Added validation for aadhar card.
=> RTEMIS-165: Added validation for aadhar card.

composer.json, config/install/user.role.state_admin.yml, patches/administerusersbyrole.patch, rte_mis.install
Ticket # : N/A
---
- Fixed the Adminsiter User By Role module issue for profiles.
=> RTEMIS-05: Fixed the Adminsiter User By Role module issue for profiles.

modules/rte_mis_core/src/Form/OverrideTermForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-164
---
- Modified the success message on term create and update.
=> RTEMIS-164: Modified the success message on term create and update.

modules/rte_mis_core/rte_mis_core.module, modules/rte_mis_gin/rte_mis_gin.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-167
---
- Fixed the tab sequencing  issue.
=> RTEMIS-167: Fixed the tab issue.

modules/rte_mis_state/rte_mis_state.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-168
---
- Restricted number of account for different user roles.
=> RTEMIS-168: Restrict Account Limit for state admin.

modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Ticket # : N/A
---
- Modified the school pdf to define dynamic entry class data.
=> RTEMIS-05: Modified the school pdf to define dynamic entry class data.

modules/rte_mis_student/js/rte_mis_student_aadhar_validation.js
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-165
---
- Modifed the verification logic for student, father, mother and guardian addhar field.
=> RTEMIS-165: Modified the js logic for addhar verification.

composer.json, modules/rte_mis_school/rte_mis_school.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-168
---
- Fixed the regression issue for School Udise Code.
- Locked the workflow module to 1.7.0
=> RTEMIS-168: Fixed the regression issue for School Udise Code.

modules/rte_mis_gin/js/register-form.js, modules/rte_mis_gin/js/script.js, modules/rte_mis_gin/rte_mis_gin.libraries.yml, modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/components/component-authority.scss, modules/rte_mis_gin/scss/layout/about-us.scss, modules/rte_mis_gin/scss/navigation/_header.scss
=> RTEMIS-138: Theming updates in about us page and menu.

modules/rte_mis_gin/scss/layout/about-us.scss, modules/rte_mis_gin/templates/node--page.html.twig
=> RTEMIS-138: Static pages theming.

config/install/menu_export.export_data.yml, config/install/user.role.school_admin.yml, config/install/views.settings.yml, config/install/views.view.allotted_student.yml, config/install/views.view.mapped_habitation.yml, config/install/views.view.school_profile.yml, modules/rte_mis_home/config/install/dashboards.dashboard.school_dashboard.yml, modules/rte_mis_home/rte_mis_home.info.yml, modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_state/rte_mis_state.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-40
---
- School Dashboard.
=> RTEMIS-40: School Admin Dashboard.

composer.json, modules/rte_mis_multilingual/config/install/rte_mis_multilingual.settings.yml, modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-174
---
-  Fixed language_switcher and hindi pdf issue.
=> RTEMIS-174: Fixed language_switcher and hindi pdf issue.

modules/rte_mis_gin/js/script.js, modules/rte_mis_gin/js/testimonial.js, modules/rte_mis_gin/scss/layout/about-us.scss, modules/rte_mis_gin/scss/navigation/_header.scss
=> RTEMIS-138: Text alignment chnages.

composer.json
=> RTEMIS-0: Added the patch for the Imported PO files issues.

modules/rte_mis_student/js/rte_mis_student_aadhar_validation.js
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-165
---
- Modified the error message for student aadhar validation.
=> RTEMIS-165: Modified the error message for student aadhar validation.

modules/rte_mis_home/rte_mis_home.module
=> RTEMIS-0: Hide the blocks when views are empty in the home page.

modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig, modules/rte_mis_student/rte_mis_student.module, modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-174
---
- Updated font settings for pdf.
=> RTEMIS-174: Updated font settings for pdf.

modules/rte_mis_core/rte_mis_core.module
Ticket # : NA
---
-  Update the page title for school admin.
=> RTEMIS-0: Update the page title for school admin.

composer.json, config/install/redirect_after_login.settings.yml, rte_mis.info.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-176
---
- Dashboard should be the default page for user.
=> RTEMIS-176: Dashboard should be the default page for user.

composer.json, config/install/menu_export.export_data.yml, config/install/sitemap.settings.yml, config/install/tour.tour.sitemap.yml, config/install/user.role.anonymous.yml, modules/rte_mis_core/src/Menu/OverrideSiteMap.php, modules/rte_mis_core/src/RteMisCoreServiceProvider.php, modules/rte_mis_gin/rte_mis_gin.libraries.yml, modules/rte_mis_gin/rte_mis_gin.module, modules/rte_mis_gin/scss/layout/sitemap.scss, modules/rte_mis_gin/scss/navigation/_footer.scss, rte_mis.info.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-178
---
- Created Sitemap for ths site.
=> RTEMIS-178: Created Sitemap for ths site.

modules/rte_mis_gin/scss/layout/sitemap.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-178
---
---
---
=> RTEMIS-178: Sitemap node school menu display block.

modules/rte_mis_core/src/Helper/RteCoreHelper.php
Ticket # : NA
---
- Set timezone for timeline events.
=> RTEMIS-0: Set timezone for timeline events.

modules/rte_mis_gin/scss/block/eligibility-criteria.scss, modules/rte_mis_home/templates/eligibility-criteria.html.twig
=> RTEMIS-170: Theming of registration closed text.

modules/rte_mis_gin/scss/layout/sitemap.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-178
---
---
---
=> RTEMIS-178: Social links sitemap theming.

config/install/menu_export.export_data.yml, config/install/redirect_after_login.settings.yml, config/install/user.role.block_admin.yml, config/install/user.role.district_admin.yml, config/install/user.role.state_admin.yml, modules/rte_mis_core/config/install/dashboards.dashboard.block_dashboard.yml, modules/rte_mis_core/config/install/dashboards.dashboard.district_dashboard.yml, modules/rte_mis_core/config/install/dashboards.dashboard.school_dashboard.yml, modules/rte_mis_core/config/install/dashboards.dashboard.state_dashboard.yml, modules/rte_mis_core/rte_mis_core.info.yml, modules/rte_mis_core/rte_mis_core.module, modules/rte_mis_core/src/Plugin/Block/RoleBasedDetailsBlock.php, modules/rte_mis_core/src/Plugin/Block/TasksStatusBlock.php, modules/rte_mis_core/templates/dynamic-dashboard-block.html.twig, modules/rte_mis_core/templates/tasks-status-block.html.twig, modules/rte_mis_gin/scss/block/tasks-status-block.scss, modules/rte_mis_home/rte_mis_home.info.yml, modules/rte_mis_school/rte_mis_school.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-172
---
- Created dashboard for diff admin roles.
=> RTEMIS-172: Created dashboard for different user roles.

composer.json, config/install/single_content_sync.settings.yml, rte_mis.info.yml
Ticket # : N/A
---
- Added the single content sync module in the dev.
---
=> RTEMIS-0: Added the single content sync module in the dev.

config/install/user.role.authenticated.yml, modules/rte_mis_core/src/Plugin/Block/RoleBasedDetailsBlock.php
Ticket # : N/A
---
- Fixed the issue of login from the block admin & added view media permission for all the roles.
---
=> RTEMIS-0: Fixed the issue of login from the block admin & added view media permission for all the roles.

modules/rte_mis_core/src/Plugin/Block/TasksStatusBlock.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-172
---
- Modified the dashboard.
=> RTEMIS-172: Modified the dashboard.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/components/component-testimonials.scss, modules/rte_mis_home/templates/eligibility-criteria.html.twig
=> RTEMIS-138: Captalize the titles and testimonial popup image size.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/components/component-testimonials.scss, modules/rte_mis_gin/scss/layout/about-us.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-175
---
---
---
=> RTEMIS-175: Static pages theming updates.

composer.json
Ticket # : N/A
---
- Updated the project details.
---
=> RTEMIS-0: Updated the project details.

modules/rte_mis_lottery/rte_mis_lottery.info.yml, rte_mis.info.yml
Ticket # : NA
---
- Added RTE-MIS Lottery Module
=> RTEMIS-00: Added Lottery module.

composer.json
Ticket # : N/A
---
- Updated the package name.
---
=> RTEMIS-0: Updated the package name.

composer.json
Ticket # : N/A
---
- Added the patch in user history module.
---
=> RTEMIS-0: Added the patch in user history module.

modules/rte_mis_school/rte_mis_school.module
Ticket # : N/A
---
- Added the checks for the usernames in inline entity form alter.
---
=> RTEMIS-0: Added the checks for the usernames in inline entity form alter.

modules/rte_mis_school/rte_mis_school.module
Ticket # : N/A
---
- Added the array diff inside the usernames validation.
---
=> RTEMIS-0: Added the array diff inside the usernames validation.

composer.json, modules/rte_mis_lottery/rte_mis_lottery.info.yml, modules/rte_mis_lottery/rte_mis_lottery.permissions.yml, modules/rte_mis_lottery/rte_mis_lottery.routing.yml, modules/rte_mis_lottery/rte_mis_lottery.services.yml, modules/rte_mis_lottery/src/Access/LotteryAccessCheck.php, modules/rte_mis_lottery/src/Batch/RandomizeStudent.php, modules/rte_mis_lottery/src/Form/LotteryForm.php, modules/rte_mis_lottery/src/Plugin/DevelGenerate/MiniNodeDevelGenerates.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-179
---
- Randomize students for lottery.
=> RTEMIS-179: Randomize students for lottery.

modules/rte_mis_core/src/Plugin/Block/SiteLogoSectionBlock.php, modules/rte_mis_gin/scss/layout/about-us.scss, modules/rte_mis_gin/scss/navigation/_footer.scss
---
- Addedhome page  link to header and footer.
=> RTEMIS-170: Added front page link to the header and footer image.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-174
---
- Theming of student pdf.
---
- Themed well.
---
=> RTEMIS-174: PDF theming and restructuring.

composer.json, patches/gin_breadcrumb_edit_fix.patch
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-175
---
- Fixed the static page breadcrumb issue.
=> RTEMIS-175: Fixed the static page breadcrumb issue.

modules/rte_mis_gin/templates/page--front.html.twig
Ticket # : N/A
---
- Added the missing brackets in the home page.
---
=> RTEMIS-0: Added the missing brackets in the home page.

modules/rte_mis_school/rte_mis_school.module, rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-183
---
- Defined the schema.
=> RTEMIS-183: Defined the schema for the School seat status table.

modules/rte_mis_core/src/Plugin/Block/RoleBasedDetailsBlock.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-172
---
- Modified the logic for different dashboards.
---
=> RTEMIS-172: Modified the logic for different dashboards.

modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-174
---
- Fixes the font issues on pdf
---
- ex: tested it on both the languages, hindi and english.
---
=> RTEMIS-174: Theming updates for the font of school pdf.

modules/rte_mis_core/src/Plugin/Block/SiteLogoSectionBlock.php
---
- Added the landing page url to banner text.
=> RTEMIS-170: Added the landing page url to banner text.

modules/rte_mis_core/src/Plugin/Block/SiteLogoSectionBlock.php, modules/rte_mis_gin/scss/navigation/_footer.scss, modules/rte_mis_gin/scss/navigation/_header.scss
---
- Theming of header and footer logo
---
- Testing of header and footer logo on different screens and browsers
=> RTEMIS-170: Header and footer logo theming.

config/install/form_mode_control.settings.yml, modules/rte_mis_student/config/optional/core.entity_form_display.mini_node.school_details.school_detail_edit.yml, modules/rte_mis_student/config/optional/core.entity_form_display.paragraph.allotted_students_details.default.yml, modules/rte_mis_student/config/optional/core.entity_view_display.paragraph.allotted_students_details.default.yml, modules/rte_mis_student/config/optional/field.field.mini_node.school_details.field_allotted_students.yml, modules/rte_mis_student/config/optional/field.field.paragraph.allotted_students_details.field_entry_class.yml, modules/rte_mis_student/config/optional/field.field.paragraph.allotted_students_details.field_medium.yml, modules/rte_mis_student/config/optional/field.field.paragraph.allotted_students_details.field_student_id.yml, modules/rte_mis_student/config/optional/field.storage.paragraph.field_student_id.yml, modules/rte_mis_student/config/optional/paragraphs.paragraphs_type.allotted_students_details.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-182
---
- Added referenced paragraph to store entry class medium and student id.
=> RTEMIS-182: Added a referrenced paragraph in school entity.

config/install/colorbox.settings.yml
---
- Fixes the modal popup on mobil screen
---
- Tested on different viewports and browsers.
=> RTEMIS-170: News popup fixes on mobil screen.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/layout/user-login-page.scss
---
- Theming of mobil and tab design of login page.
---
- For different browsers and different viewports.
=> RTEMIS-138: Login page mobil and tab theming fixes.

modules/rte_mis_school/rte_mis_school.module
Ticket # : N/A
---
- Fixed the udise not showing issue in the user register form.
=> RTEMIS-0: Fixed the udise not showing issue.

composer.json, composer.lock, config/install/user.role.state_admin.yml, config/install/views.view.lottery_results.yml, modules/rte_mis_lottery/config/install/rte_mis_lottery.settings.yml, modules/rte_mis_lottery/config/install/view_custom_table.tables.yml, modules/rte_mis_lottery/rte_mis_lottery.info.yml, modules/rte_mis_lottery/rte_mis_lottery.install, modules/rte_mis_lottery/rte_mis_lottery.links.menu.yml, modules/rte_mis_lottery/rte_mis_lottery.module, modules/rte_mis_lottery/rte_mis_lottery.routing.yml, modules/rte_mis_lottery/rte_mis_lottery.services.yml, modules/rte_mis_lottery/src/Access/StudentSmsAccessCheck.php, modules/rte_mis_lottery/src/Batch/PrepareLotteryData.php, modules/rte_mis_lottery/src/Batch/SendSmsBatch.php, modules/rte_mis_lottery/src/Commands/LotteryCommands.php, modules/rte_mis_lottery/src/Controller/LotteryController.php, modules/rte_mis_lottery/src/Form/LotteryConfigForm.php, modules/rte_mis_lottery/src/Form/SendSmsConfirmForm.php, modules/rte_mis_lottery/src/Plugin/DevelGenerate/LotteryDataDevelGenerates.php, modules/rte_mis_lottery/src/Plugin/QueueWorker/StudentDataQueue.php, modules/rte_mis_lottery/src/Services/RteLotteryHelper.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-184
---
- Added Lottery results view.
=> RTEMIS-184: Added Lottery results view.

modules/rte_mis_home/rte_mis_home.info.yml
Ticket # : NA
---
- Update the module name.
=> RTEMIS-0: Update the module name.

config/install/menu_export.export_data.yml, config/install/views.view.lottery_results.yml, modules/rte_mis_lottery/drush.services.yml, modules/rte_mis_lottery/rte_mis_lottery.services.yml, modules/rte_mis_lottery/src/Commands/LotteryCommands.php, modules/rte_mis_lottery/src/Plugin/DevelGenerate/MiniNodeDevelGenerates.php, modules/rte_mis_lottery/src/Services/RteLotteryHelper.php, modules/rte_mis_student/rte_mis_student.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-184
---
- Added menu, drush command, and fixed issues.
=> RTEMIS-184: Added menu, drush command and fixed issues.

config/install/gin.settings.yml
Ticket # : N/A
---
- Updated the favicon path.
---
=> RTEMIS-0: Updated the favicon path.

modules/rte_mis_gin/scss/base/_global.scss
Ticket # :
---
- Lottery form table theming.
---
- Tested on different screen sizes and multiple browsers.
=> RTEMIS-179: Lottery form table theming.

scripts/lottery/process_lottery_data.sh
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-179
---
- Added script for lottery processing.
=> RTEMIS-184: Added script for processing lottery.

modules/rte_mis_gin/scss/base/_global.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-172
---
- Added scroll effectfor mobil screen in table of block admin.
---
- Tested on different screen sizes and multiple browsers.
=> RTEMIS-172: Added scroll effect in table on mobil screen.

modules/rte_mis_lottery/rte_mis_lottery.install, modules/rte_mis_lottery/src/Controller/LotteryController.php, modules/rte_mis_lottery/src/Form/LotteryForm.php, modules/rte_mis_lottery/src/Plugin/QueueWorker/StudentDataQueue.php, modules/rte_mis_lottery/src/Services/RteLotteryHelper.php, scripts/lottery/process_lottery_data.sh
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-184
---
-  Added lottery_id in seat_status table.
=> RTEMIS-184: Added lottery_id in seat_status table.

modules/rte_mis_lottery/rte_mis_lottery.services.yml, modules/rte_mis_lottery/src/Batch/PrepareLotteryData.php, modules/rte_mis_lottery/src/Form/LotteryForm.php, modules/rte_mis_lottery/src/Services/RteLotteryHelper.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-184
---
- Optimized the randomize process.
=> RTEMIS-184: Optimized the randomize process.

modules/rte_mis_gin/scss/components/component-testimonials.scss, modules/rte_mis_gin/scss/layout/homepage.scss, modules/rte_mis_gin/scss/navigation/_header.scss
---
- Resolved homepage theming issues.
---
- Tested on different viewpoerts and browsers.
=> RTEMIS-138: Homepage theming issues.

config/install/views.view.allotted_students_details.yml, modules/rte_mis_allocation/rte_mis_allocation.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-187
---
- Admission Status Page for Schools.
- Created a menu link under Student menu link.
=> RTEMIS-187: Admission Status Page for Schools.

modules/rte_mis_lottery/src/Form/LotteryForm.php, modules/rte_mis_lottery/src/Plugin/QueueWorker/StudentDataQueue.php, modules/rte_mis_mail/rte_mis_mail.module, scripts/lottery/process_allocation_student_queue.sh
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-189
---
- Added time-limit parameter in lottery script.
- Added script for processing allocation student queue.
- Fixed issue of re-randomise schools
=> RTEMIS-184: Added time-limit parameter in lottery script.

config/install/user.role.school_admin.yml, config/install/views.view.allotted_students_details.yml, modules/rte_mis_allocation/rte_mis_allocation.module, modules/rte_mis_allocation/rte_mis_allocation.services.yml, modules/rte_mis_allocation/src/Access/AllocationDetailEditAccessCheck.php, modules/rte_mis_allocation/src/Routing/RouteSubscriber.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-187
---
-  Added exposed filters.
-  Added academic cycle constraint.
-  Added a routeSubscriber for allocation edit check.
=> RTEMIS-187: Added exposed filter.

modules/rte_mis_gin/scss/base/_global.scss
---
- Remove the spinbox globally.
=> RTEMIS-138: Fixed the spinbox on input field issue.

config/install/form_mode_control.settings.yml, config/install/user.role.school_admin.yml, config/install/views.view.allotted_students_details.yml, modules/rte_mis_allocation/config/install/core.entity_form_display.mini_node.allocation.allocation_status.yml, modules/rte_mis_allocation/config/install/core.entity_form_display.workflow_transition.student_admission_workflow.default.yml, modules/rte_mis_allocation/config/install/core.entity_form_mode.mini_node.allocation_status.yml, modules/rte_mis_allocation/config/install/core.entity_view_display.mini_node.allocation.allocation_details.yml, modules/rte_mis_allocation/config/install/core.entity_view_display.mini_node.student_details.allocation_details.yml, modules/rte_mis_allocation/config/install/core.entity_view_display.workflow_transition.student_admission_workflow.default.yml, modules/rte_mis_allocation/config/install/core.entity_view_mode.mini_node.allocation_details.yml, modules/rte_mis_allocation/config/install/field.field.workflow_transition.student_admission_workflow.field_district.yml, modules/rte_mis_allocation/config/install/field.field.workflow_transition.student_admission_workflow.field_other_school.yml, modules/rte_mis_allocation/config/install/field.field.workflow_transition.student_admission_workflow.field_state.yml, modules/rte_mis_allocation/config/install/field.storage.workflow_transition.field_district.yml, modules/rte_mis_allocation/config/install/field.storage.workflow_transition.field_other_school.yml, modules/rte_mis_allocation/config/install/field.storage.workflow_transition.field_state.yml, modules/rte_mis_allocation/config/install/rte_mis_allocation.settings.yml, modules/rte_mis_allocation/rte_mis_allocation.module, modules/rte_mis_allocation/src/Access/AllocationDetailEditAccessCheck.php, modules/rte_mis_student/src/Access/StudentDetailViewAccessCheck.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-190
---
- Added view for allocation details in student mini_node.
=> RTEMIS-190: Added view for allocation details in student mini_node.

config/install/menu_export.export_data.yml, config/install/user.role.block_admin.yml, config/install/user.role.district_admin.yml, config/install/user.role.state_admin.yml, modules/rte_mis_allocation/rte_mis_allocation.links.menu.yml, modules/rte_mis_allocation/rte_mis_allocation.permissions.yml, modules/rte_mis_allocation/rte_mis_allocation.routing.yml, modules/rte_mis_allocation/src/Access/AllocationDetailEditAccessCheck.php, modules/rte_mis_allocation/src/Controller/StudentAdmissionReportController.php, modules/rte_mis_core/src/Plugin/Block/RoleBasedDetailsBlock.php, modules/rte_mis_gin/scss/base/_global.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-188
---
- Student Admission Report Page for States.
- Added a condition check for Allocation edit access check.
- Optimized the roleBasedDetailBlock.
---
=> RTEMIS-188: Student Admission Report Page for States.

modules/rte_mis_gin/scss/base/_global.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-190
---
- Theming of student allocation section.
---
- Tested on mobil and tab devices with different browsers.
=> RTEMIS-190: Student allocation section theming.

patches/select2_reference_specific_field_value.patch
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-186
---
- Added the validation for the default value from the element.
---
=> RTEMIS-186: Added the validation for the default value from the element.

composer.json, composer.lock
Ticket # : N/A
---
- Updated the symlinks for the favicon.
---
=> RTEMIS-0: Updated the symlinks for the favicon.

modules/rte_mis_allocation/rte_mis_allocation.module, modules/rte_mis_lottery/src/Plugin/DevelGenerate/MiniNodeDevelGenerates.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-203
---
- Added field for student data in the devel_generate plugin.
=> RTEMIS-203: Added field for student data in devel_generate plugin.

README.md
Ticket # :
---
- Added Features in the readme file.
---
=> RTEMIS-138: Added Features in the readme file.

modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-225
---
- Fixed the regression issue for weights.
=> RTEMIS-225: Fixed the regression issue for weights.

composer.json, composer.lock, config/install/form_mode_control.settings.yml, config/install/menu_export.export_data.yml, config/install/user.role.block_admin.yml, config/install/user.role.district_admin.yml, config/install/user.role.school_admin.yml, config/install/user.role.state_admin.yml, config/install/views.view.student_tracking_dashboard.yml, modules/rte_mis_student_tracking/config/install/core.entity_form_display.mini_node.student_performance.student_tracking_modify.yml, modules/rte_mis_student_tracking/config/install/core.entity_form_mode.mini_node.student_tracking_modify.yml, modules/rte_mis_student_tracking/rte_mis_student_tracking.module, rte_mis.info.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-198
---
-  Added a view.
-  Added a menu link for the same.
-  Modified user roles permission.
-  Added a form mode.
=> RTEMIS-198: Added Student Tracking Dashboard for School Admin.

composer.json
=> RTEMIS-0: Locked the version for view custom table module.

composer.json, composer.lock
=> RTEMIS-0: Updated the select2 patch path.

composer.json, composer.lock
Ticket # : N/A
---
- Added the patch for the issue of initial class save for block_class.
---
=> RTEMIS-0: Added the patch for the issue of initial class save for block_class.

config/install/block_class.settings.yml
=> RTEMIS-0: Added the patch for the block class issue.

config/install/views.view.allotted_students_details.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-187
---
- Modified the path and no result text for the allocated-student view.
=> RTEMIS-187: Modified the path and no result text for the allocated-student view.

modules/rte_mis_allocation/config/install/core.entity_form_display.workflow_transition.student_admission_workflow.default.yml, modules/rte_mis_student/src/Access/StudentDetailViewAccessCheck.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-190
---
- Modified the weight of contact number & alternative contact number.
=> RTEMIS-190: Modified the weight of contact number & alternative contact number.

modules/rte_mis_gin/scss/layout/about-us.scss
---
- Font size updation for about us page.
---
- Tested on different browsers and screen sizes.
=> RTEMIS-138: Updated font size on about us page.

modules/rte_mis_gin/scss/layout/about-us.scss
---
-  About us page list items color changed.
---
- Tested on different browsers.
=> RTEMIS-138: About us page list items color changed.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_student_tracking/rte_mis_student_tracking.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-229
---
- Have themed the student tracking module.
---
- Tested on different browsers with different viewports.
=> RTEMIS-229: Student tracking dashboard theming.

modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_final_grade.yml, modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_final_rank.yml, modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_student.yml, modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_total_attendance.yml, modules/rte_mis_student_tracking/rte_mis_student_tracking.module, modules/rte_mis_student_tracking/rte_mis_student_tracking.services.yml, modules/rte_mis_student_tracking/src/Access/PerformanceDetailEditAccessCheck.php, modules/rte_mis_student_tracking/src/Routing/RouteSubscriber.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-199
---
- Added access check for student performance.
- Added logic for workflow change for allocation entity.
- Remove required from some fields.
=> RTEMIS-199: Added access check and workflow state change logic.

config/install/menu_export.export_data.yml, config/install/views.view.allotted_students_details.yml, config/install/views.view.lottery_results.yml, modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_lottery/rte_mis_lottery.module, modules/rte_mis_lottery/rte_mis_lottery.routing.yml, modules/rte_mis_lottery/src/Form/LotteryForm.php, modules/rte_mis_lottery/src/Form/SendSmsConfirmForm.php, modules/rte_mis_lottery/src/Services/RteLotteryHelper.php, modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-179
---
- Design the buttons for lottery results.
- Modified the school pdf twig.
- Fixed all the lottery issues.
---
- Tested on different browsers and on different breakpoints.
=> RTEMIS-179: Fixed all the lottery issues.

modules/rte_mis_gin/scss/navigation/_header.scss
---
- Changed the color of menu link which dosent consist of any link.
---
- Tested on different browsers with all login instances.
=> RTEMIS-138: Menu with no link color updated.

modules/rte_mis_core/rte_mis_core.module, modules/rte_mis_student_tracking/rte_mis_student_tracking.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-198
---
- Modified the logic as per latest discussion.
- Only the previous data can be altered.
- Current year data cannot be altered.
=> RTEMIS-198: Modified the logic for student tracking dashboard.

modules/rte_mis_gin/scss/base/_global.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-229
---
- Fixes the box shadow on click of any class.
---
- Tested on different browsers and different breakpoints.
=> RTEMIS-229: Student tracking dashboard theming updates.

modules/rte_mis_student_tracking/src/Batch/StudentTrackingBatch.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-201
---
- Fixed invalid religion issue on import.
---
- Tested bulk import with empty religion.
---
=> RTEMIS-201: Fixed religion issue and removed unnecessary checks.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_student_tracking/src/Batch/StudentTrackingBatch.php
=> Merge `main` to `qa`

modules/rte_mis_gin/scss/navigation/_header.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-204
---
- Changed the color of menus for logged in users which dosent consist of any link.
---
- Tested on different browsers.
=> RTEMIS-204: Color change of logged menu which dosent consist of any link.

modules/rte_mis_student_tracking/config/install/core.entity_form_display.mini_node.student_performance.default.yml, modules/rte_mis_student_tracking/config/install/core.entity_form_display.mini_node.student_performance.student_tracking_modify.yml, modules/rte_mis_student_tracking/src/Access/PerformanceDetailEditAccessCheck.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-198
---
- Fixed the select2 list issue.
- Modified the access check.
=> RTEMIS-198: Fixed the select2 issue and modified the access check.

modules/rte_mis_lottery/src/Plugin/QueueWorker/StudentDataQueue.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-183
---
- Modified the logger message.
=> RTEMIS-183: Modified the logger message for the lottery allocation.

config/install/menu_export.export_data.yml, modules/rte_mis_allocation/rte_mis_allocation.routing.yml, modules/rte_mis_allocation/src/Controller/StudentAdmissionReportController.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-188
---
- Modified the allortment report menu link.
- Added a new menu link 'student admission report' dashboard.
---
---
=> RTEMIS-188: Modified the menu links and added a new menu link.

modules/rte_mis_allocation/src/Controller/StudentAdmissionReportController.php, modules/rte_mis_gin/scss/base/_global.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-251
---
- Themed the allotment repport page.
---
- Tested on different viewports and different browsers.
=> RTEMIS-251: Allotment report page theming.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_gin/scss/navigation/_header.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-258
---
- Fixes the alignment of academic session node.
---
- Tested on different browsers with different viewports.
=> RTEMIS-258: FE issues for logged in users.

config/install/block.block.gin_twocolumnblock.yml, modules/rte_mis_core/rte_mis_core.services.yml, modules/rte_mis_core/src/Helper/ConfigManager.php, modules/rte_mis_home/rte_mis_home.module, rte_mis.install, rte_mis.profile
=> RTEMIS-0: Invalidating the cache tags of the home page when updating the entity queue.

config/install/views.view.student_tracking_dashboard.yml, modules/rte_mis_core/rte_mis_core.inc, modules/rte_mis_student_tracking/config/install/core.entity_form_display.mini_node.student_performance.default.yml, modules/rte_mis_student_tracking/config/install/core.entity_form_display.mini_node.student_performance.student_tracking_modify.yml, modules/rte_mis_student_tracking/config/install/core.entity_view_display.mini_node.student_performance.allocation_details.yml, modules/rte_mis_student_tracking/config/install/core.entity_view_display.mini_node.student_performance.default.yml, modules/rte_mis_student_tracking/config/install/core.entity_view_display.mini_node.student_performance.pdf.yml, modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_academic_session_tracking.yml, modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_student_application_number.yml, modules/rte_mis_student_tracking/config/install/field.storage.mini_node.field_academic_session_tracking.yml, modules/rte_mis_student_tracking/rte_mis_student_tracking.install, modules/rte_mis_student_tracking/rte_mis_student_tracking.module, modules/rte_mis_student_tracking/rte_mis_student_tracking.services.yml, modules/rte_mis_student_tracking/src/Access/PerformanceDetailViewAccessCheck.php, modules/rte_mis_student_tracking/src/Routing/RouteSubscriber.php, rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-198
---
-  Added access check to view entity.
- Modified options for academic session & entry year.
- Modified the student tracking dashboard view.
- Added field for student application number.
- Added field for student application number.
- Modified the workflow transition for the student application number field.
---
---
=> RTEMIS-198: Modifed the student performance entity.

modules/rte_mis_logs/js/logging.js, modules/rte_mis_logs/js/scroll-to-top.js, modules/rte_mis_logs/rte_mis_logs.libraries.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-256
---
=> RTEMIS-256: Modified the logs panel.

modules/rte_mis_core/rte_mis_core.inc, modules/rte_mis_student_tracking/rte_mis_student_tracking.module
Ticket # : N/A
---
- Performance entity will be created only when the admission session is active.
=> RTEMIS-0: Added the condition check for academic session check.

modules/rte_mis_gin/js/script.js, modules/rte_mis_gin/scss/base/_global.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-264
---
- View panel for filelog entries theming
---
- Tested on different browsers and viewports.
=> RTEMIS-264: View panel for filelog entries theming.

rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-202
---
- Fixed re-declared hook_update() function.
---
---
=> RTEMIS-202: Fixed re-declared hook_update() function.

config/install/views.view.student_tracking_dashboard.yml, modules/rte_mis_student_tracking/src/Batch/StudentTrackingBatch.php, rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-201
---
- Added a check to restrict student import if there is duplicate entry for application number.
- Added student name field in students tracking dashboard view.
---
- Verified that student import is restricted if there is duplicate entry for application number in the sheet or student performance already exists for the entered application number.
-  Verifeid that student name is displayed on studnets tracking dashboard table.
---
=> RTEMIS-201: Restrict duplicate entries for application numbers during students import.

modules/rte_mis_gin/scss/base/_global.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-229
---
- Student tracking dashboard theming updates for tab.
---
- Tested on different browsers and viewports.
=> RTEMIS-229: Student tracking dashboard theming for tab.

modules/rte_mis_allocation/rte_mis_allocation.module, modules/rte_mis_allocation/rte_mis_allocation.services.yml, modules/rte_mis_allocation/src/Services/RteAllocationHelper.php, modules/rte_mis_lottery/rte_mis_lottery.install, modules/rte_mis_lottery/rte_mis_lottery.services.yml, modules/rte_mis_lottery/src/Controller/LotteryController.php, modules/rte_mis_lottery/src/Plugin/QueueWorker/StudentDataQueue.php, modules/rte_mis_lottery/src/Services/RteLotteryHelper.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-261
---
- Fixed lottery status data issue in API for external lottery.
- Handled the allocation dropout case when lottery is run again.
- Added allocation details and status section on student details for students.
---
- Verified that all the listed bugs are fixed.
---
=> RTEMIS-261: Fixed lottery and student allocation bugs.

modules/rte_mis_student_tracking/src/Commands/StudentTrackingCommandsForTesting.php, modules/rte_mis_student_tracking/src/Plugin/QueueWorker/StudentTrackingQueue.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-202
---
- Sets application number field value during auto promotion. 
- And some minor changes in testing commands to make testing easier.
---
- Tested that student application number is added successfully when new student performance node is created.
---
=> RTEMIS-202: Set application number field value during auto promotion.

modules/rte_mis_allocation/rte_mis_allocation.module, modules/rte_mis_allocation/src/Services/RteAllocationHelper.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-261
---
- Fixed regression issue for student application status.
---
- Tested that the regression is fixed.
---
=> RTEMIS-261: Fixed regression issue for student application status.

modules/rte_mis_logs/config/install/rte_mis_logs.settings.yml, modules/rte_mis_logs/js/logging.js, modules/rte_mis_logs/rte_mis_logs.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-256
---
- Added date field
=> RTEMIS-256: Updated the PR with the created column and removed filter fields.

docs/admission.html, docs/appadmin.html, docs/index.html, docs/lottery.html, docs/school.html, docs/state.html, docs/student.html
=> added G-tag

modules/rte_mis_gin/scss/base/_global.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-264
---
- View panel for filelog entries theming
---
- Tested on different browsers and viewports.
=> RTEMIS-264: View panel logs theming updates.

modules/rte_mis_reimbursement/config/install/core.entity_form_display.mini_node.state_fees_details.default.yml, modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.state_fees_details.default.yml, modules/rte_mis_reimbursement/config/install/eck.eck_type.mini_node.state_fees_details.yml, modules/rte_mis_reimbursement/config/install/field.field.mini_node.state_fees_details.field_academic_year.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.info.yml, rte_mis.info.yml, rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-269
---
- Created a new module for the reimbursement work
=> RTEMIS-269: Added the module for the reimbursement and created one field for academic year.

modules/rte_mis_reimbursement/config/install/core.entity_form_display.mini_node.state_fees_details.default.yml, modules/rte_mis_reimbursement/config/install/core.entity_form_display.paragraph.state_fees.default.yml, modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.state_fees_details.default.yml, modules/rte_mis_reimbursement/config/install/core.entity_view_display.paragraph.state_fees.default.yml, modules/rte_mis_reimbursement/config/install/field.field.mini_node.state_fees_details.field_state_fees.yml, modules/rte_mis_reimbursement/config/install/field.field.paragraph.state_fees.field_board_type.yml, modules/rte_mis_reimbursement/config/install/field.field.paragraph.state_fees.field_fees_amount.yml, modules/rte_mis_reimbursement/config/install/field.field.paragraph.state_fees.field_fees_type.yml, modules/rte_mis_reimbursement/config/install/field.storage.mini_node.field_state_fees.yml, modules/rte_mis_reimbursement/config/install/field.storage.paragraph.field_fees_amount.yml, modules/rte_mis_reimbursement/config/install/field.storage.paragraph.field_fees_type.yml, modules/rte_mis_reimbursement/config/install/paragraphs.paragraphs_type.state_fees.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.info.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-269
---
- Added field for fees details and board type.
=> RTEMIS-269: Added the paragraph state fees and it's three fields.

config/install/views.view.lottery_results.yml, modules/rte_mis_lottery/asset/format.json, modules/rte_mis_lottery/src/Controller/LotteryController.php, modules/rte_mis_lottery/src/Form/LotteryForm.php, modules/rte_mis_lottery/src/Form/SendSmsConfirmForm.php, modules/rte_mis_lottery/src/Plugin/QueueWorker/StudentDataQueue.php, modules/rte_mis_lottery/src/Services/RteLotteryHelper.php, rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-275
---
- Modified the condition to fetch the students.
- Modified the lottery result view.
- Modified the sms sending condition to check for the allocation id.
=> RTEMIS-275: Added the unallotted student for the next lottery condition.

modules/rte_mis_allocation/rte_mis_allocation.module, modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_lottery/src/Services/RteLotteryHelper.php, modules/rte_mis_student/config/install/views.view.student_applications.yml, modules/rte_mis_student/rte_mis_student.install, modules/rte_mis_student/rte_mis_student.views.inc, modules/rte_mis_student/src/Plugin/views/field/StudentApplicationStatusField.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-261
---
- Updated student application field to also show allocation status.
---
---
=> RTEMIS-261: Updated student application field to also show allocation status.

modules/rte_mis_lottery/rte_mis_lottery.views.inc, modules/rte_mis_lottery/src/Plugin/views/field/StudentApplicationStatusField.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-261
---
- Moved Student application status view field to rte mis lottery module. 
---
- Tested that the feature is working as expected and no errors are there.
---
=> RTEMIS-261: Moved Student application status view field to rte mis lottery module.

config/install/user.role.state_admin.yml, modules/rte_mis_reimbursement/config/install/rte_mis_reimbursement.settings.yml, modules/rte_mis_reimbursement/config/schema/rte_mis_reimbursement.schema.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.links.menu.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.permissions.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.routing.yml, modules/rte_mis_reimbursement/src/Form/RteMisReimbursementConfigForm.php, rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-268
---
- Adds configuration form for reimbursement settings.
---
- Tested that all the fields are present as per the requirement and stored in config properly.
- Tested the form validations.
---
=> RTEMIS-268: Added rte mis reimbursment configuration form.

modules/rte_mis_core/rte_mis_core.inc, modules/rte_mis_reimbursement/config/install/core.entity_form_display.paragraph.state_fees.default.yml, modules/rte_mis_reimbursement/config/install/field.field.paragraph.state_fees.field_fees_amount.yml, modules/rte_mis_reimbursement/config/install/field.field.paragraph.state_fees.field_fees_type.yml, modules/rte_mis_reimbursement/config/install/field.storage.paragraph.field_fees_type.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.info.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.module, rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-269
---
- Added checkboxes for fee type.
- Added callback for default value.
=> RTEMIS-269: Added checkboxes for fee type.

rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-268
---
- Modified the update hook.
=> RTEMIS-268: Modified the update hook.

modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_education_details.yml, modules/rte_mis_school/rte_mis_school.install, modules/rte_mis_school/rte_mis_school.module, rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-277
---
- Added condition for education details check.
- Made the education details section required
---
=> RTEMIS-277: Added condition for education details check.

modules/rte_mis_school/rte_mis_school.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-277
---
- Added category check for both "Boys" and "Co-ed" or both "Girls" and "Co-ed" entries.
=> RTEMIS-277: Added condition for category on education details.

modules/rte_mis_allocation/src/Controller/StudentAdmissionReportController.php, modules/rte_mis_core/rte_mis_core.inc, modules/rte_mis_core/src/Plugin/Menu/AlterTaxonomyActionTask.php, modules/rte_mis_lottery/src/Services/RteLotteryHelper.php, modules/rte_mis_reimbursement/rte_mis_reimbursement.module, modules/rte_mis_reimbursement/rte_mis_reimbursement.services.yml, modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php, modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_state/rte_mis_state.module, modules/rte_mis_state/src/Plugin/Menu/AlterPeopleActionTask.php, modules/rte_mis_student/src/CustomVocabularyListBuilder.php, modules/rte_mis_student_tracking/rte_mis_student_tracking.module, modules/rte_mis_student_tracking/src/Plugin/QueueWorker/StudentTrackingQueue.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-270
---
- Moved the redundant code to service.
- Added the table in the mini node view.
=> RTEMIS-270: Added the code to reimbursement service.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_reimbursement/rte_mis_reimbursement.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-286
---
- Reimbursement student tracking node theming.
---
- Tested on different browsers and viewports.
=> RTEMIS-286: Reimbursement student tracking node theming.

modules/rte_mis_school/config/install/core.entity_view_display.mini_node.school_details.default.yml, modules/rte_mis_school/config/install/core.entity_view_display.mini_node.school_details.pdf.yml, modules/rte_mis_school/rte_mis_school.install, modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-284
---
- Added board type to pdf format.
=> RTEMIS-284: Added board type to pdf format.

modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-284
---
- Removed the title for board type.
=> RTEMIS-284: Removed the title for board type.

modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_reimbursement/rte_mis_reimbursement.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-270
---
- Modified the ajax callback.
=> RTEMIS-270: Changed class attribute to id.

modules/rte_mis_mail/src/Form/RteMisMailConfigForm.php, modules/rte_mis_reimbursement/rte_mis_reimbursement.info.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.module
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-283
---
- Configured mail and sms trigger on reimbursement claim status change.
- Configurable from the backend/App Admin.
=> RTEMIS-283: Configured the sms and mail services on claim status change.

modules/rte_mis_reimbursement/rte_mis_reimbursement.module, modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-270
---
- Modified claim entity validation to check for different users.
=> RTEMIS-270: Modified claim entity validation.

config/install/user.role.state_admin.yml, config/install/views.view.reimbursement_claim.yml, modules/rte_mis_core/rte_mis_core.inc, modules/rte_mis_reimbursement/config/install/core.entity_form_display.mini_node.school_claim.default.yml, modules/rte_mis_reimbursement/config/install/core.entity_form_display.paragraph.state_fees.default.yml, modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.school_claim.allocation_details.yml, modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.school_claim.default.yml, modules/rte_mis_reimbursement/config/install/core.entity_view_display.paragraph.state_fees.default.yml, modules/rte_mis_reimbursement/config/install/field.field.mini_node.school_claim.field_academic_session_claim.yml, modules/rte_mis_reimbursement/config/install/field.field.paragraph.state_fees.field_education_level.yml, modules/rte_mis_reimbursement/config/install/field.storage.mini_node.field_academic_session_claim.yml, modules/rte_mis_reimbursement/config/install/rte_mis_reimbursement.settings.yml, modules/rte_mis_reimbursement/config/schema/rte_mis_reimbursement.schema.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.module, modules/rte_mis_reimbursement/rte_mis_reimbursement.services.yml, modules/rte_mis_reimbursement/src/Access/SchoolClaimEditAccessCheck.php, modules/rte_mis_reimbursement/src/Access/SchoolClaimViewAccessCheck.php, modules/rte_mis_reimbursement/src/Form/RteMisReimbursementConfigForm.php, modules/rte_mis_reimbursement/src/Routing/RouteSubscriber.php, modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-290
---
- Modified the school claim entity to have dynamic academic year.
- Added access checks for school claim entity.
- Modified the user permissions.
- Added education level to the school fee details entity.
=> RTEMIS-290: Modified the school fee detail entity & claim entity.

config/install/views.view.reimbursement_claim.yml, modules/rte_mis_reimbursement/config/install/core.entity_form_display.mini_node.school_claim.school_claim_modify.yml
---
- Changed field name for academic year in view and form mode.
=> RTEMIS-280: Change academic year field in school claim modify form mode.

modules/rte_mis_reimbursement/rte_mis_reimbursement.module, modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
---
- Added access checks for update operation for reimbursement status.
---
- Tested that all roles have update link visibility based on reimbursement status as per expectation.
---
=> RTEMIS-280: Added access checks for update operation for reimbursement status.

modules/rte_mis_reimbursement/config/install/workflow.state.reimbursement_claim_workflow_approved_by_beo.yml, modules/rte_mis_reimbursement/config/install/workflow.state.reimbursement_claim_workflow_payment_completed.yml, modules/rte_mis_reimbursement/config/install/workflow.state.reimbursement_claim_workflow_rejected.yml, modules/rte_mis_reimbursement/config/install/workflow.state.reimbursement_claim_workflow_reset.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_approved_by_beo_reset.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_approved_by_deo_reset.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_creation_reset.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_completed_payment_completed.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_completed_reset.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_pending_payment_pending.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_pending_reset.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_rejected_reset.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_reset_approved_by_beo.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_reset_approved_by_deo.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_reset_payment_completed.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_reset_payment_pending.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_reset_rejected.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_reset_reset.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_reset_submitted.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_submitted_reset.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.module, modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
---
- Adds reset claim state for disctrict and block admins to reset reimbursement claim request.
---
- Tested that block/district are able to reset the claim request.
---
=> RTEMIS-280: Added reset reimbursement claim request feature.

config/install/user.role.block_admin.yml, config/install/views.view.student_tracking_dashboard.yml, modules/rte_mis_gin/rte_mis_gin.module, modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_reimbursement/rte_mis_reimbursement.module, modules/rte_mis_student_tracking/config/install/core.entity_view_display.mini_node.student_performance.allocation_details.yml, modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_dropout_studying.yml, modules/rte_mis_student_tracking/config/install/workflow.workflow.student_tracking_workflow.yml, modules/rte_mis_student_tracking/rte_mis_student_tracking.install, modules/rte_mis_student_tracking/rte_mis_student_tracking.module, rte_mis.install
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-289
---
---
---
=> RTEMIS-289: Added student tracking dashboard for block admin.

config/install/form_mode_control.settings.yml, config/install/user.role.block_admin.yml, config/install/views.view.academic_sessions_list.yml, modules/rte_mis_core/src/EventSubscriber/RouteRedirectSubscriber.php, modules/rte_mis_reimbursement/rte_mis_reimbursement.links.action.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.module, modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.school_fee_modify.yml, modules/rte_mis_school/config/install/core.entity_form_mode.mini_node.school_fee_modify.yml, modules/rte_mis_school/rte_mis_school.module, modules/rte_mis_school/rte_mis_school.services.yml, modules/rte_mis_school/src/Access/SchoolDetailEditAccessCheck.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-287
---
- Added the feature for the block to edit school fee during reimbursement window.
- Added a view for school details and given permission to block to edit.
- Modified the school details access check
- Added View for state fee details and given permission to create/modify.
- Added redirect logic for school claim entity.
=> RTEMIS-287: Added the feature for the block to edit school fee. 

config/install/views.view.reimbursement_claim.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.module, modules/rte_mis_reimbursement/rte_mis_reimbursement.services.yml, modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
---
- Fixed the regression issue.
- Added rest button on reimbursement claim view.
=> RTEMIS-280: Fixed the regression issue.

config/install/user.role.block_admin.yml, config/install/user.role.district_admin.yml, config/install/user.role.school_admin.yml, config/install/views.view.academic_sessions_list.yml, modules/rte_mis_gin/scss/base/_global.scss, modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.school_claim.pdf.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.module, modules/rte_mis_reimbursement/src/Routing/RouteSubscriber.php, modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php, modules/rte_mis_reimbursement/templates/eck-entity--mini-node--school-claim--pdf.html.twig, modules/rte_mis_school/src/Access/SchoolPdfDownloadAccessCheck.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-282
---
- Added the school claim entity pdf print feature.
=> RTEMIS-282: Added the school claim entity pdf print feature.

modules/rte_mis_core/rte_mis_core.inc, modules/rte_mis_student_tracking/src/Plugin/QueueWorker/StudentTrackingQueue.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-289
---
- Updates the logic of education completed to create new student performance entity.
- Code optimizations.
---
- Tested that all students except dropped out are promoted to new class.
=> RTEMIS-289: Updated student tracking promotion for education complete scenario and code optimization.

modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.school_claim.pdf.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-282
---
- Modified the field view values for claim entity.
=> RTEMIS-282: Modified the field view values for claim entity.

config/install/views.view.student_tracking_dashboard.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.module, modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php, modules/rte_mis_reimbursement/templates/eck-entity--mini-node--school-claim--pdf.html.twig
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-282
---
- Modified the logic for regression issues.
=> RTEMIS-282: Modified the code.

config/install/views.view.student_tracking_dashboard.yml, modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.school_claim.pdf.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.module, modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php, modules/rte_mis_reimbursement/templates/eck-entity--mini-node--school-claim--pdf.html.twig
=> Merge main to qa

modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
=> RTEMIS-282: Fixed the upper_primary issue.

config/install/user.role.block_admin.yml
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-290
---
-  Added the permission for block admin to use the school claim modify form mode.
=> RTEMIS-290: Modified the permission for block admin.

config/install/views.view.reimbursement_claim.yml, modules/rte_mis_reimbursement/config/install/rte_mis_reimbursement.settings.yml, modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_reset_submitted.yml, modules/rte_mis_reimbursement/config/install/workflow.workflow.reimbursement_claim_workflow.yml, modules/rte_mis_reimbursement/config/schema/rte_mis_reimbursement.schema.yml, modules/rte_mis_reimbursement/rte_mis_reimbursement.module, modules/rte_mis_reimbursement/rte_mis_reimbursement.services.yml, modules/rte_mis_reimbursement/src/Access/SchoolClaimEditAccessCheck.php, modules/rte_mis_reimbursement/src/Plugin/QueueWorker/ResetReimbursementClaimQueue.php, modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php, scripts/reimbursement/process_reimbursement_claim_queue.sh
---
- Adds feature to auto reset reimbursement claim on state or school fee details changes.
- Claim status update from reset to submit when claim is re-submitted.
- Restrict submit of same claim if reset limit exceeds.
---
- Tested that claim is auto reset when school or state fee details are updated.
- Tested that claim is not re-submitted if reset limit exceeds.
---
=> RTEMIS-280: Reset reimbursement claim when state or school fees details are updated.

modules/rte_mis_reimbursement/rte_mis_reimbursement.module, modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
---
- Fixes the issue when creating a new school fees details entity.
- Updated reset count logic.
---
- Tested that school fees details entity is saved properly now.
---
=> RTEMIS-280: Fixed school fees details update issue.

config/install/views.view.reimbursement_claim.yml
---
- Adds the reset option in the reimbursement claim status fiter.
---
- Tested that reset option is available in the reimbursement claim status fiter.
---
=> RTEMIS-280: Added reset option in the reimbursement claim status fiter.

modules/rte_mis_reimbursement/rte_mis_reimbursement.module
---
- Fixed regression for single approval level workflow.
---
- Tested that district is able to update the claim status if single level approval is enabled.
---
=> RTEMIS-280: Fixed regression for single approval level workflow.

modules/rte_mis_gin/scss/base/_global.scss
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-297
---
`Added minimum height to the access denied page text.
---
`Tested on all pages with different browsers and screen sizes.
=> RTEMIS-297: Access denied page theming.

modules/rte_mis_report/rte_mis_report.routing.yml, modules/rte_mis_report/src/Controller/HabitationMappingReportDashboard.php, modules/rte_mis_report/src/Form/HabitationReportForm.php, modules/rte_mis_report/src/Services/RteReportHelper.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-294
---
- Added a report dashboard for school habitation mapping check.
=> RTEMIS-294: Added a report dashboard for school habitation mapping.

modules/rte_mis_report/src/Controller/SchoolInformationReportSchoolList.php, modules/rte_mis_report/src/Controller/SchoolRegistrationReportBlockController.php, modules/rte_mis_report/src/Form/SchoolRegistrationReportFilterForm.php, modules/rte_mis_report/src/Services/RteReportHelper.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-296
---
- Adds education level and board type filters school registration report page.
=> RTEMIS-296: Added education level and board type filters for school registration report.

modules/rte_mis_report/src/Controller/HabitationMappingReportDashboard.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-294
---
- Added safe checks for empty values.
=> RTEMIS-294: Modified the logic for empty values.

composer.json, composer.lock, patches/user_history_warning_msg_removed.patch
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-294
---
- Upgraded to Drupal 10.2.10
- Removed the warning message for user history.
---
=> RTEMIS-294: Fixed the security updates.

modules/rte_mis_report/src/Controller/SchoolRegistrationReportController.php, modules/rte_mis_report/src/Form/HabitationReportForm.php, modules/rte_mis_report/src/Services/RteReportHelper.php
Ticket # : https://innoraft.atlassian.net/browse/RTEMIS-294
---
- Fixed regression issues.
-  Added condition for location check on udise filter.
=> RTEMIS-294: Fixed regression issues.

patches/select2_reference_specific_field_value.patch
Ticket # : RTEMIS-0
---
- Fix a warning occurring in the select2 module.
---
=> RTEMIS-0: Updating the patch file of the select2 module for removing a warning.

composer.json, composer.lock
Ticket # : RTEMIS-0
---
- Updated the location of the options module patch.
---
=> RTEMIS-0: Updated the options module patch location.

composer.json, composer.lock
Ticket # : RTEMIS-0
---
- Updated the location of the patch file.
---
=> RTEMIS-0: Updated the location of the patch file.
